### ISSUE TITLE
Clingo en mac

### ISSUE THREAD

**Issue by fran-gl** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#1]
Hola! No me queda claro cómo instalar clingo en Mac OS.
Si tengo homebrew, basta con correr ```brew install clingo```?

Muchas gracias de antemano.

**Comment by nbarriav** [comment]
Hola! Si, con eso basta para instalarlo

**Comment by fran-gl** [comment]
Ok, muchas gracias!
