### ISSUE TITLE
Duda sobre ubicación de personas

### ISSUE THREAD

**Issue by BrunoFarfan** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#10]
Hola!
Quería saber si hay cuando no se nos dice nunca donde se ubica una persona, entonces nuestros modelos deben incluir cada posible punto de partida para cada tiempo posible, o si hay alguna restricción que debamos suponer (siempre parten en el metro en el tiempo inicial, por ejemplo).

**Comment by FeBalla** [comment]
No sé si me quedó muy clara la pregunta, pero no hay ninguna restricción de ubicación de las personas, siempre y cuando se trate de una versión válida, esto es:
* La gente que sabemos que estuvo en cierto lugar, en cierto tiempo, esté ahí. *
* El culpable haya estado en el lugar del crimen antes del descubrimiento
* No hayan 2 personas en el mismo lugar al mismo tiempo.
* ...

Esto significa que no hay necesidad de que partan en algún lugar determinado o cosas del estilo. Eso sí, **tener en cuenta todas las restricciones** mencionadas (y no mencionadas), al igual que las de desplazamiento (una arista del grafo por tiempo)-

**Comment by BrunoFarfan** [comment]
Eso quiere decir, por ejemplo, que si la persona X estuvo en el tiempo 3 en L, nuestro código puede no mostrar ninguna ubicación para X en tiempos menores a 3, o debe mostrar posibles lugares en los que estuvo?

**Comment by FeBalla** [comment]
En la versión válida, **todos deben tener asignados una ubicación para cada instante de tiempo**. Pueden haber varios modelos, pero todos deben tener asignados una posición y deben cumplir las restricciones señaladas antes.
