### ISSUE TITLE
Problemas Actividad 7, parte 1

### ISSUE THREAD

**Issue by ignacioarteaga99** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#100]
Al cargar un archivo de audio `.wav` que esta en el mismo directorio o carpeta que el notebook, me arroja el siguiente error:
![image](https://user-images.githubusercontent.com/48535635/174424463-c35b6dcd-fbde-490d-b00f-cbf2ac1320e6.png)

Así mismo, se genera el siguiente archivo de audio: audio_part, aunque este es irreproducible. Creo que el error se puede estar generando porque el archivo de audio dura más de 30 segundos, pero tengo entendido que el método `get_mfccs` de esta actividad manejaba dichos casos. De todos modos no sé a qué se deba este error y estoy siguiendo tal cual se hace en la cápsula.

![image](https://user-images.githubusercontent.com/48535635/174424544-8d1b0a79-6c04-4e7d-ace3-4374796345bf.png)

**Comment by ignacioarteaga99** [comment]
Me parece que el problema está con el "audio_part.wav", porque sí pude trabajar con el otro mediante otras funciones

**Comment by vicentevegaulloa** [comment]
Hola @ignacioarteaga99!

Pensamos que el problema podría estar en cómo corres el notebook. ¿Podrías darnos más detalles de cómo lo estás corriendo?  Si no me equivoco es jupyter pero, ¿Cómo corres el notebook en jupyter?¿Qué comando usas?

Para ahorrarte tiempo, otras formas de resolver que se nos ocurren es quizás abrir el notebook en colab, o vscode y ver si de esa forma te funciona. También podrías intentar probando `get_mfcc()` con otras canciones y contarnos si cambia algo. Por último, podrías probar usando el PATH completo en caso de que hubieses estado probando con el PATH relativo.

**Comment by installg3ntoo** [comment]
Hola, yo igual he tenido ese problema, en mi caso he ocupado visual studio code para visualizar los jupyters junto a Python 3.9.6. Corro la función con el PATH relativo y el PATH real y en ambos casos me muestra el mismo error que @ignacioarteaga99.

![image](https://user-images.githubusercontent.com/53901814/175192786-260c7205-482d-455b-a05c-8aa56cb6141a.png)

**Comment by vicentevegaulloa** [comment]
Hola!

Viendo ambos problemas, los dos tienen en común que trabajan localmente con el notebook. Encontré [esta](https://github.com/jiaaro/pydub/issues/542) issue donde se sugieren tres formas de resolver el problema. Al parecer en su instalación hubo un problema con un `.exe` de la librería. Para evitar meter mano en temas de instalación (que por lo general es bastante engorroso), creo que primero deberían intentar trabajar con GoogleColab, dado que el ambiente es más "universal". 

Intenten eso y estaré atento en caso de que no les funcione. Ojalá les resulte 🤞

**Comment by gamoedo1** [comment]
Yo tuve el mismo problema, y encontré que agregando la extensión en el método 'export' de la línea ... funciona bien. Quedaría como:

audio_part.export("audio_part.wav","wav")
