### ISSUE TITLE
Formato de entrega T4 parte 2

### ISSUE THREAD

**Issue by albertoar1** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#101]
En el enunciado de la tarea se pide entregar todo en Jupyter, pero los códigos de la parte 2 son en python, entonces tengo que copiarlos a un Jupyter y entregar eso o rellenar los .py y subir un pdf para las partes escritas?

**Comment by FeBalla** [comment]
Sí, es un detalle que se nos pasó, pero para la primera parte son _notebooks_ y para la segunda los .py con un PDF para las respuestas.
