### ISSUE TITLE
Clasificación de audios T4

### ISSUE THREAD

**Issue by BrunoFarfan** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#102]
Hola!

Por la forma en la que las canciones están partidas 10 segmentos, me surgió la duda de si hay que clasificar cada segmento individualmente, o hay que clasificar la canción por completo?
Por la forma en la que se tratan los datos me hace entender que se clasifican los segmentos individualmente, sin embargo, el enunciado habla de clasificar canciones, lo que me hace pensar en que se refiere a los 30 segundos por completo.

En el caso de que se clasifiquen los segmentos de 3 segundos individualmente, para la parte de clasificar el género de una canción a nuestra elección, tenemos que ver cual es el género que más se repite entre sus segmentos o hacer alguna estimación similar?

**Comment by FeBalla** [comment]
Se clasifican los segmentos, ya que de este modo se puede tener más datos para el entrenamiento. De todos modos, esto es porque se trata de un ejemplo práctico, pero en un contexto real pueden usar segmentos más largos o incluso la canción completa.
