### ISSUE TITLE
Duda mfccs archivo input

### ISSUE THREAD

**Issue by installg3ntoo** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#103]
Hola, tenía la duda con respecto al archivo que nos dan, el archivo `mfcc_data.json` porque se supone que para cada segmento que dura 3 segundos se le calculó sus mfccs. Pero se supone que se pueden obtener 13 mfccs por cada 0.023 segundos de canción (utilizando librosa). Por lo que no entiendo si para cada segmento tenemos 13 mfccs y si ese es el caso, cual sería la diferencia entre sacar 13 mfccs cada 3 segundos vs sacar 13 mfccs cada 0.023 segundos?

**Comment by vicentevegaulloa** [comment]
Hola @installg3ntoo!

Usamos 3 segundos porque consideramos que es una cantidad de tiempo prudente para poder reconocer el género de una canción. Recuerda que sobre cada segmento se hace la predicción del género musical, y usamos segmentos porque si usamos canciones completas tendríamos muy pocos datos. Es por esto que al pensar en el tamaño que debían tener los segmentos buscamos un tiempo que fuera razonable para poder reconocer el género de una canción, y también tener una cantidad significativa de inputs. Si utilizaramos 0.023 segundos tendríamos muchos más inputs para el modelo, pero es tan poco tiempo para reconocer el género de una canción, que sería como pasarle solo ruido a la red.

Espero haber respondido tu preugnta. Si no te queda claro siéntete libre de seguir preguntando 😄

**Comment by installg3ntoo** [comment]
Si, gracias ya me quedó claro.
