### ISSUE TITLE
Tarea 4 - Parte 1.1 Dataset GTZAN 

### ISSUE THREAD

**Issue by Jesusdelgad** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#104]
Un consulta para la actividad 1 de redes neuronales, para escoger la canción debemos usar un .wav de la dataset GTZAN?, y si es así esta base de datos la descargamos desde google o esta subida en algún repositorio?

**Comment by vicentevegaulloa** [comment]
Hola @Jesusdelgad ! 

Efectivamente, debes usar una canción de GTZAN. El link al dataset en Kaggle está en las referencias del enunciado ([este es](https://www.kaggle.com/datasets/andradaolteanu/gtzan-dataset-music-genre-classification)). Recuerda que no debes adjuntarla en el repositorio, ya que con el nombre nos va a bastar para hallarla.
