### ISSUE TITLE
[T4] Datos Parte 1

### ISSUE THREAD

**Issue by fran-gl** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#105]
Hola! No me queda claro el formato del dataset de la parte 1 de la tarea.

Cada dato del tipo:
```
[
    -57.79621505737305,
    62.886131286621094,
    30.897022247314453,
    40.34696578979492,
    18.241439819335938,
    17.448444366455078,
    25.284761428833008,
    -4.945111274719238,
    4.776095390319824,
    22.534141540527344,
    1.8476824760437012,
    0.5736892223358154,
    -6.7256622314453125
]
```
¿corresponde a todos los MFCCs de un segmento de una canción? ¿o es **un** MFCC de un segmento de una canción? Me parece que estos datos están agrupados de a 130, entonces no estoy segura.

Muchas gracias de antemano.

**Comment by SarahEverke** [comment]
Hola!
Hay un MFCC por segmento, como una canción se divide en diez segmentos hay 10 MFCC por canción. Además, un MFCC corresponde a una matriz de 130 x 13.

**Comment by fran-gl** [comment]
Ok, perfecto, muchas gracias!
