### ISSUE TITLE
[T4] Accuracy Parte 1

### ISSUE THREAD

**Issue by fran-gl** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#107]
Hola! Cuando en la parte 1 de la tarea dice que la accuracy debe ser mayor al 40% o 50% en el set de entrenamiento, ¿esto debe ser en todas las épocas o solo se considera la última?

Muchas gracias de antemano.

**Comment by FeBalla** [comment]
Debe ser en la última, porque hasta entonces la red aún no termina de estar entrenada, por lo que no tiene sentido. Luego, esa red entrenada deben evaluarla sobre el set de test también

**Comment by fran-gl** [comment]
Oka, muchas gracias!
