### ISSUE TITLE
[DCClue] - Ubicaciones iniciales de las personas

### ISSUE THREAD

**Issue by fvaldes17** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#11]
Hola! 
Respecto a las ubicaciones iniciales de las personas, ¿podemos asumir que siempre existirán?
Por ejemplo, en el documento `prob1.lp` existen cuatro personas, pero solo se tienen las ubicaciones iniciales de dos personas:

(Extraído del documento `prob1.lp` entregado para la tarea):
`persona(nacho).
persona(nico).
persona(felipe).
persona(fernando).`

`personaEnLugar(nico, cai, 1).
personaEnLugar(fernando, cai, 5).`

En este caso no tenemos la ubicación inicial ni de felipe ni de nacho. 
¿Se puede asumir que si no tienen ubicaciones iniciales entonces las personas no podrán hacer aseveraciones obre ellos?

** Por ubicaciones iniciales entiéndase que es sabida la ubicación de alguien, de manera externa (como una verdad absoluta).
Muchas gracias!

**Comment by vWing7** [comment]
Hola, si no se tiene una ubicación de alguien, sí se pueden hacer aseveraciones sobre esta persona, es decir, en ese caso podrías tener, por ejemplo, que fernando dice que nacho estaba en metro en el tiempo 2.
