### ISSUE TITLE
[T4 P2: Aprendizaje Reforzado] Duda sobre estados del juego

### ISSUE THREAD

**Issue by ShescBlank** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#110]
Hola :D

Estaba implementando mi Q-Table y guardando el resultado en el csv pedido, pero al observar el archivo (luego de entrenar durante bastante tiempo al modelo) me di cuenta de que muchos estados nunca ocurren, es decir, hay muchas entradas de la tabla que se mantienen en 0. Intenté hacer varias cosas para que se forzaran otros estados pero tampoco cambió mucho la situación.

Como última idea, volví al código original, para ver si había roto alguna parte, y también me retornó muy pocos estados únicos, alrededor de 220-224 de los 3168 posibles teóricamente (esto con NUM_EPISODES = 50000).

¿Puede ser que algo esté pasando y que haya muchos estados que nunca ocurran?

Muchas gracias! 🐧

**Comment by dfloreaa** [comment]
Hola @ShescBlank, en general es poco frecuente que la pelota de tres botes a lo largo del mapa (y es imposible para algunas combinaciones de parámetros en el estado). Similar es el caso para dos rebotes.

Es debido a esto que algunas entradas en tu QTable nunca ocurrirán (por limitaciones físicas del juego), y por ende no debes preocuparte por ellas. En todo caso, buena observación :)

Avísame si quedas con alguna duda al respecto, un saludo
