### ISSUE TITLE
[T4 P2: Aprendizaje Reforzado] Duda sobre el cálculo de las recompensas

### ISSUE THREAD

**Issue by ShescBlank** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#112]
Hola de nuevo :D perdón por las dos issues hoy

Luego de entrenar durante bastante tiempo a mi jugador, me di cuenta de que siempre pierde de la misma forma: cuando la pelota rebota arriba y el pádel se encuentra abajo de ella. Decidí poner prints (en cada frame) en la función ```play_step()``` del archivo ```PongAI.py``` en los tres ifs que calculan el reward, líneas 176, 184 y 192. Entonces si el pádel debe bajar, imprime "moverse hacia abajo"; si debe subir, "moverse hacia arriba"; y si se debe quedar quieto, "quedarse quieto". Esto lo hice porque dependiendo de si la acción elegida en ```get_action``` coincide con lo de arriba, entonces reward=1 y -1 en caso contrario.

La cosa es que al correr una simulación obtuve la siguiente imagen:

![image](https://user-images.githubusercontent.com/53873288/175839155-fc168a95-757e-47b8-9b15-825aa00dfbaf.png)

La pelota viene de rebotar en el techo y el programa está recompensando con 1 si el pádel baja, cuando, en mi opinión, debería subir o quedarse quieto. Este caso es justo lo que ocurre con mi agente entrenado, decide bajar cuando la pelota viene de esta forma, lo que provoca que pierda.

¿Puede ser que este sea un caso borde en que la recompensa no se esté calculando bien? Pareciera que esto solo ocurre cuando la pelota rebota y no siempre, hay varios casos en que sí se da la instrucción correcta.

Seguiré investigando por si encuentro algo.

Muchas gracias 😄

**Comment by dfloreaa** [comment]
Hola, en QLearning muchas veces el Agente puede comportarse de formas no deseadas justo cuando creemos que va a hacerlo de forma correcta y no es poco frecuente (nos ocurrió harto lo que tu indicas mientras diseñábamos la tarea). En general esto se debe a como asignamos la recompensa o bien la forma en que discretizamos los estados.

Te recomiendo entrenar más a tu agente o bien cargar la QTable y "forzarlo" a cambiar la conducta mediante una rutina cortta de entrenamiento que esté solo basada en esa interacción. 

Espero que te ayuden mis comentarios, saludos :)

**Comment by aalmuna** [comment]
Hola, muchas gracias por la respuesta!
Intentaré lo de cargar la QTable y forzarlo a cambiar su conducta, porque sin importar cuanto lo entrene, mi agente siempre se equivocará en esa situación debido a que la recompensa lo premia por alejarse de la pelota.
Muchas gracias de nuevo :D
