### ISSUE TITLE
[T4 P2] Error proximidad pádel

### ISSUE THREAD

**Issue by sebaguerrap** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#113]
Hola, me di cuenta que en el archivo `QAgent.py` en la clase `Agent` en el método `get_state` se tiene 
```python
proximity = 5 - int(round(game.ball.x / game.MAX_X) * 5)
```

Sin embargo, `game.ball.x / game.MAX_X` siempre toma un valor entre 0 y 1 por lo que `proximity` siempre va a tomar el valor 0 ó 5. La pregunta es si podemos modificar este método para arreglar el problema.

**Comment by vicentevegaulloa** [comment]
Hola! 

Efectivamente es un error. Puedes arreglarlo si quieres cambiando de lugar el paréntesis, así:
```
proximity = 5 - int(round((game.ball.x / game.MAX_X) * 5))
```
En todo caso, es posible entrenar al agente correctamente sin ese cambio, por si alguien ve esto y ya terminó.
