### ISSUE TITLE
T4 P1: Actividad 3 "aplanar la matriz"

### ISSUE THREAD

**Issue by sofiagiagnoni** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#114]
Hola!

Tengo una duda respecto a lo que aparece en la ayudantía 10. Si no utilizo la técnica de aplanar la matriz, entonces tensorboard grafica de forma correcta. Sin embargo, no puedo calcular la accuracy porque aparece el siguiente error: ValueError: Input 0 of layer "sequential_7" is incompatible with the layer: expected shape=(None, 16900), found shape=(None, 130, 13). Además, tampoco puedo generar el plot_history a lo largo de las épocas. Ocurre lo mismo si aplico la técnica de aplanar la matriz tal cual como aparece en la ayudantía. En cambio, si considero aplanar la matriz pero con input_size = (image_size * image_size) //10 entonces puedo hacer el cálculo de la accuracy y tensorboard pero no puedo graficar  plot_history 

¿Qué debería hacer al respecto?

(No estoy modificando ningún parámetro respecto a lo que aparece la ayudantía. Los set de test, validation y train son calculados se forma correcta). 

Saludos

**Comment by FeBalla** [comment]
Esto es respecto a la red densa o convolucional? Me llama la atención este error porque no termino de entenderlo del todo 😕 No deberías tener problemas con la interfaz de tensorboard. En todo caso, también puedes graficar con matplotlib si es que efectivamente fuera problema de eso (aunque lo dudo). Quizás si haces un _commit_ a tu repo podría entender mejor lo que está pasando.

**Comment by sofiagiagnoni** [comment]
Hola! Pude arreglarlo explicitando de forma correcta el tamaño de input_size según los tramos de los segmentos y mfcc. 

Muchas gracias!
