### ISSUE TITLE
T4 P1 Actividad 7: Descargar la canción desde Spotify o YouTube

### ISSUE THREAD

**Issue by sofiagiagnoni** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#115]
Hola!

Estoy teniendo problemas para descargar una canción de Spotify o YouTube. En el caso de Spotify solo me deja manejarla desde la Biblioteca y en el caso de YouTube, exige ser usuario Premium o suscribirse por 4.100 CLP. ¿Existe alguna forma de descargar una canción gratis? ¿Podría grabarse desde un celular externo mientras se ejecuta la canción para generar el archivo.wav necesario? ¿Podría ser uno de los audios de la base de datos de kaggle utilizada?

Quedo atenta a su respuesta
Saludos Sofía

**Comment by vicentevegaulloa** [comment]
Hola!

[Esta](https://www.bensound.com/free-music-for-videos) es una página donde puedes descargar música gratis sin tener problemas de copyright. Se descarga en mp3 pero la puedes convertir a wav con una página como [esta](https://cloudconvert.com/mp3-to-wav). Espero que eso te sirva!

**Comment by sofiagiagnoni** [comment]
Perfecto! Otra duda, puede ser que la accuracy me de 0 al pasarle una nueva canción que no está en la db pese a que, al entrenar la red, la accuracy y val_accuracy son mayores a 50%? O debería dar un valor mayor a 0?

Saludos!

**Comment by vicentevegaulloa** [comment]
Podría pasar. Al final el modelo que entrenaste no te da un 100% de accuracy, por ende, si te da un 60% existe un 40% de probabilidad de que no le acierte al género de una nueva canción. Espero que se entienda esa lógica.

**Comment by sofiagiagnoni** [comment]
Sii, gracias!
