### ISSUE TITLE
T4 P1 Actividad 7: función eval_model

### ISSUE THREAD

**Issue by sofiagiagnoni** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#117]
Hola! Estoy probando con eval_model evaluar el modelo entrenado a partir de una canción fuera del dataset original. Sin embargo, cuando uso la función tal cual está me tira el error:

ValueError: Input 0 of layer "sequential_4" is incompatible with the layer: expected shape=(None, 16900), found shape=(None, 130, 13, 1)

¿Qué dimensiones debiesen tener X_song e y_song antes de entrar a la función?

Mi CNN tiene valores de accuracy y val_accuracy mayores al 50%

Quedo atenta a su respuesta

Saludos

**Comment by FeBalla** [comment]
Hola!
Por el error, me hace pensar que definiste mal las dimensiones de _input_ de la red neuronal. Me da la sensación que quizás definiste las dimensiones de entrada como todo el set de datos completo y no los de cada fila. En la cápsula se ve un pequeño ejemplo de cómo definir la CNN, por lo que debería ser más que suficiente con eso y luego añadirle más capas densas o convolucionales según les parezca mejor.

Intenté revisar tu repo, pero no hay ningún _commit_, por lo que no puedo saber bien qué estás haciendo. Te recomendaría revisar la cápsula, donde se crean las dimensiones de entrada. Esto porque si usas `Sequential`, el resto de los _input shapes_ se definen automáticamente.

**Comment by sofiagiagnoni** [comment]
Hola! Pude arreglarlo agregando a to_categorical un parámetro que explicita las dimensiones.

muchas gracias!
