### ISSUE TITLE
Tarea 4 - P2: Formato q_table

### ISSUE THREAD

**Issue by Felopo** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#118]
Hola!. Cuando guardo la Q-Table en un .csv, esta se guarda en una sola columna con todos los valores de esta separados por coma. Mi duda es si este es el **formato** requerido? O se quiere que nuestro .csv tenga el **formato** de 8 columnas (de la A a la H en excel) como mencionan en la cápsula y enunciado?

Tengo esta duda porque en general los archivos .csv son como el primer formato que comento, y los .xlsx tienen el segundo formato que comento, que es el formato pedido en el enunciado (campos separados por celdas), por lo que pensaba que quizá sea mejor un .xlsx.

De antemano muchas gracias!

**Comment by vicentevegaulloa** [comment]
Hola!

Se requiere que el formato sea `.csv` donde cada fila esté separada por un salto de línea y cada elemento de la fila (representando las columnas) esté  separado por comas. Algo así:

![image](https://user-images.githubusercontent.com/48890894/176724824-b1e1af1f-f96c-41ae-96ea-d7c67f956820.png)

Este formato sí se puede obtener tanto con `.csv` y con `.xlsx`, pero nosotros pedimos que lo guarden como `.csv`.

Espero haber aclarado tu duda. Si aún no te queda claro estaré atento para responderte 😄

**Comment by Felopo** [comment]
Sii, quedó super claro. Muchas gracias!!

**Comment by mjsifri** [comment]
Hola, la q_table tiene que ser de 3168 * 8 columnas? o eso es solo para exportarla al .csv?
