### ISSUE TITLE
Supuesto en DCCajas

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#12]
Hola!

Tengo una duda en la parte de DCCajas, quería saber si podemos suponer que nunca ocurrirá que un robot (sin caja) tenga más de una caja adyacente? Por ejemplo que R esté en (0,0) y que tanto en (0,1) como en (1, 0) haya una caja.

Gracias de antemano!

**Comment by andrescf** [comment]
Hola! No se puede asumir que solo habrá una caja adyacente al robot todo el tiempo.
Exito!
