### ISSUE TITLE
T4 P2 Actividad 2: Dimensiones Q-Table vs. q_table.csv

### ISSUE THREAD

**Issue by sofiagiagnoni** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#120]
Hola!

En el método init me queda la duda de si las dimensiones de la Q-Table corresponden a 3168 filas y 3 columnas considerando solo los q_values o  3168 filas y 8 columnas  (estados + q_values). Entiendo que se espera que el archivo q_table.csv tenga 3168 filas y 8 columnas. Sin embargo, no me queda claro para la Q-Table del método init.

Quedo atenta a su respuesta 

Saludos!

**Comment by vicentevegaulloa** [comment]
Hola!

La estructura de datos que ocupen para la Q-Table en el código es libre, siempre y cuando cumpla con lo que les pedimos y permita el uso de Q-Learning como corresponde. Lo lógico sería que agrupen los valores de estado y los utilicen como índice para localizar fácilmente sus Q-Values en la Q-Table. 

Una vez hayan realizado eso y les funcione, deben acomodar su Q-Table a lo que les pedimos en el csv.
