### ISSUE TITLE
Tarea 4 Parte 1 Actividad 6

### ISSUE THREAD

**Issue by Jesusdelgad** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#122]
Hola estoy incluyendo mi propia canción a la red pero tengo un problema que no he podido entender hasta ahora es sobre el tamaño de X e y, no se como trabajarlos correctamente, porque se que para X se agrega otra columna, pero hasta ahí no más llego.
![Error](https://user-images.githubusercontent.com/80914510/176826656-b2867e04-d75f-4d36-a569-5461f86385af.png)
.

**Comment by FeBalla** [comment]
Hola!
Sin ver el código es difícil saber cuál es el problema. Evidentemente, lo que está pasando es que las dimensiones que les estás dando no coinciden. Si pasas 10 segmentos, entonces deben haber 10 _labels_, una para cada segmento. Es obvio quizás, pero es complejo saber sin más detalles, por si pudieras especificar más.
