### ISSUE TITLE
T4 P2 Bonus

### ISSUE THREAD

**Issue by sofiagiagnoni** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#123]
Hola!

Respecto al Bonus, en el enunciado se declara que existe un formulario en Canvas para inscribirse. Sin embargo, he buscado en la plataforma y no lo he encontrado. ¿Está disponible?

Saludos!

**Comment by FeBalla** [comment]
Hola!
Ya lo liberamos en [este form](https://forms.gle/aTK8oBToWihwK2Kn8).
