### ISSUE TITLE
[T4] Duda comportamiento torneo

### ISSUE THREAD

**Issue by ShescBlank** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#124]
Hola :D

Quería comentar que implementé el cambio descrito en la issue #113  porque me hizo mucho sentido a otra issue anterior que hice. Este cambio modifica bastante los estados que se llenan en la QTable y me ayudó a mejorar los resultados de mi entrenamiento. A partir de lo anterior, me surge la duda de que esta modificación podría afectar el rendimiento del torneo dependiendo de la fórmula que se utilice para obtener los estados del juego (podría consultar estados para los que el agente no fue entrenado o viceversa). Quería preguntar si se van a usar nuestros códigos para hacerlos competir (lo que tomaría en cuenta este tipo de cambios) o se va a utilizar algún código más global? No sé si se entiende mi duda.

Muchas gracias de antemano y les deseo un muy buen viernes ☔

**Comment by vicentevegaulloa** [comment]
Hola!

El cambio que se hizo fue de una línea de código y habilita 3 nuevas posibilidades para el valor de proximidad. Al ser un error de código, en la teoría nosotros si habíamos considerado todas las posibilidades de la componente proximidad. Esto quiere decir que en el tamaño de la q_table que les pedimos si consideramos las 5 proximidades, por lo tanto, no es necesario su código y bastará con usar la q-table en formato `csv `que suban al form.

Espero que se haya entendido.

Feliz viernes!

**Comment by aalmuna** [comment]
A lo que voy es que va a haber agentes entrenados bajo los 5 estados de proximidad y otros con 2. Entonces, si el código entrega estados con las 5 proximidades, podría ocurrir que se consulten filas de las tablas que están con puros 0, ya que algunos agentes fueron entrenados bajo otro contexto. Y algo parecido en el caso contrario

**Comment by vicentevegaulloa** [comment]
En este caso hemos decidido revisar la Q-Table de los participantes para identificar si ocuparon 2 o 5 proximidades, y correrlas bajo el código que le funcione a cada una, es decir, con o sin el cambio de en el código.
