### ISSUE TITLE
T2 P1 Actividad 7

### ISSUE THREAD

**Issue by oscars810** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#125]
Hola! 
El get_mfcc retorna 10 mfcc en la cancion que le pasemos, por lo tanto, mi cnn retornará un arreglo de 10x10 (Un vector con cada probabilidad de los label por cada mfcc). 
Entonces, mi pregunta es si podemos modificar el codigo para que el predict se haga por cada mfcc que le pasemos.

**Comment by FeBalla** [comment]
Nosotros proponemos esa arquitectura de red, pero pueden hacer los cambios que estimen convenientes, siempre y cuando los expliquen y justifiquen correctamente 😄
