### ISSUE TITLE
T4 P2 altura del balón con respecto del padel

### ISSUE THREAD

**Issue by smrebolledo** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#126]
En el código que nos entregan la forma de clasificar los cuadrantes no coincide con lo descrito y con la foto del enunciado, en cambio si coincide con la imagen de la cápsula, mi pregunta es que forma de clasificar debemos ocupar?

**Comment by FeBalla** [comment]
No me termina de quedar claro a qué te refieres, podrías explicarlo con una imagen y/o código? por favor?

**Comment by smrebolledo** [comment]
El código escrito aquí coincide con esta imagen, pero no es así como está en el enunciado
![image](https://user-images.githubusercontent.com/42575575/177060067-2a012009-2a86-491c-a762-c9708375dcee.png)
![image](https://user-images.githubusercontent.com/42575575/177060101-1306d31e-b7db-4dbb-af2d-89d1a2f97268.png)

**Comment by FeBalla** [comment]
¿En qué no coincide?

**Comment by smrebolledo** [comment]
El del enunciado es así, el 0 y 1 difieren
![image](https://user-images.githubusercontent.com/42575575/177060249-dce68744-f309-4e97-ab10-42f18a8851ba.png)

**Comment by FeBalla** [comment]
Sí, aparentemente es un error del enunciado ahora que lo veo. De todos modos, no debería causarles muchos problemas 😄
