### ISSUE TITLE
[T4 P2] Cálculo new_q_value

### ISSUE THREAD

**Issue by fguinez** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#128]
Tengo una duda sobre cómo calcular el `new_q_value`. En las diapos de la cápsula sale una fórmula que utiliza `argmax Q[x_i]` y `argmax Q[x_{i+1}]`, ¿no deberían ser `max Q[x_i]` y `max Q[x_j]`?

Dado que, según entiendo, lo que nos interesa para calcular el nuevo `q_value` es el `q_value` anterior, no la acción correspondiente a ese `q_value`. En este caso, `argmax` nos indica la acción y `max` nos indica el valor de esa acción.

Adjunto la diapositiva correspondiente:

![Screen Shot 2022-07-02 at 17 53 57](https://user-images.githubusercontent.com/26127246/177017555-685477f8-29e0-4651-ab1b-fd226f1f3dcc.png)

**Comment by dfloreaa** [comment]
Efectivamente, es más un tema de nomenclatura utilizada en la literatura, pero para propósitos de su implementación debería ser _max_ en vez de _argmax_ dado que este último indica la acción a realizar y no su calidad asociada
