### ISSUE TITLE
[T4] Bases de Campeonato 

### ISSUE THREAD

**Issue by ceosorio** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#129]
Hola! En los anuncios se habló de que subirían las reglas para el campeonato, pero no encontré nada :(

En específico queria preguntar por algun tipo de restricción que haya para entrenar a nuestros agentes (por ejemplo, que no pueda editarse el código que nos entregaron, o si tal vez se puede modificar la politica de recompensas, o hacer arreglos en las formulas)

Saludos!

**Comment by FeBalla** [comment]
Hola!
Las reglas son las que corren sobre el código base. Los cambios en recompensas o todo eso no aplican. El único cambio que tendremos en consideración es el que se menciona en #124, que lo revisaremos de forma automática para adaptarlo.

**Comment by dfloreaa** [comment]
En todo caso, @ceosorio recuerda que al jugar con el modelo no importa realmente como decidiste modelar tus recompensas, ya que solo consultaremos la Q-Table ya entrenada para decidir cómo el agente se va a comportar. Un saludo :)

**Comment by ceosorio** [comment]
> En todo caso, @ceosorio recuerda que al jugar con el modelo no importa realmente como decidiste modelar tus recompensas, ya que solo consultaremos la Q-Table ya entrenada para decidir cómo el agente se va a comportar. Un saludo :)

@dfloreaa Preguntaba por lo mismo, porque si hago una modificación, mi entrenamiento es mucho más eficiente (y llega a mucho mejores resultados al probarlo), pero no tengo claro si está permitido ya que no lo entrené con las mismas reglas que los demás.

Entonces, no se si puedo subir mi q_table o no, porque podría ser considerado 'trampa'
