### ISSUE TITLE
Duda sobre mentiras DCClue

### ISSUE THREAD

**Issue by BrunoFarfan** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#13]
Hola!
Quería saber si es que a nuestro código se le introducirán situaciones en las que por ejemplo ocurra una situación imposible en la que una persona afirma que otra se desplaza 3 caminos en 2 tiempos, por ejemplo. Lo pregunto porque en ese caso habría que entrar a ver la distancia entre ubicaciones y no solo si hay un camino que las conecta y por lo que entiendo esa materia no debería entrar.

**Comment by CataAlamos** [comment]
Hola! Esta situación no va a ocurrir ya que no es un hecho, pero puede ocurrir como una afirmación. Es decir, alguien puede decir que paso tal evento, pero realmente no paso.

**Comment by BrunoFarfan** [comment]
Pero entonces habría que detectar que miente? Eso es lo que me tiene un poco enredado.

**Comment by CataAlamos** [comment]
Te tiene enredado la parte de detectar como miente, o otra?

**Comment by BrunoFarfan** [comment]
O sea, es que si por ejemplo tenemos a una persona A, que está en un lugar L1 en el tiempo 1, y la persona B afirma que afirma que A está en un lugar L4 en el tiempo 3, entonces habrían en este caso 3 lugares entre L1 y L4, pero solo pasaron 2 tiempos, por lo que es una mentira dicha afirmación.
Lo que pregunto es si nuestro código tendría que detectar un problema de ese tipo. Más general, sería detectar si es que alguien afirma que la distancia desplazada es más grande de lo que posiblemente podría haberse desplazado la otra persona en ese tiempo.

**Comment by CataAlamos** [comment]
Su código debe detectar este tipo de problemas, ya que no es posible desplazarse una distancia tan grande en el tiempo dado. Quedo atenta a cualquier otra pregunta.
