### ISSUE TITLE
[T1] Valores dentro de predicados clingo

### ISSUE THREAD

**Issue by fran-gl** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#14]
Hola! Me surgió la duda de si se pueden reemplazar los valores de solo algunas variables en un predicado de clingo o no. Por ejemplo, en la parte de DCCajas de la T1, para representar que una caja está en el suelo se puede escribir ```boxOn(B,X,Y,0,T)```? O debería ser de otra manera, como```boxOn(B,X,Y,Z,T), Z=0.```?

Muchas gracias de antemano.

**Comment by FeBalla** [comment]
Ambas formas deberían ser equivalentes, ya que estás generando la misma información!

**Comment by fran-gl** [comment]
Ok, gracias!
