### ISSUE TITLE
[DCClue] - Duda sobre lugar de descubrimiento

### ISSUE THREAD

**Issue by fvaldes17** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#15]
Hola!
Sobre la mentira y la ubicación del lugar de descubrimiento: ¿Ambas deben cumplirse para que una persona sea culpable? es decir, ¿no podría ocurrir que el culpable mienta pero no haya estado anteriormente en el lugar de descubrimiento, o bien que el culpable no mienta y haya estado anteriormente en el lugar de descubrimiento?
Muchas gracias!

**Comment by FeBalla** [comment]
Podría darse que el culpable no mienta, porque derechamente no haya dicho nada o algo del estilo. Sin embargo, sí o sí debe haber estado en el lugar del crimen antes del tiempo del descubrimiento.

De todos modos, podría ser que ustedes no tengan suficiente información para afirmar cualquiera de las 2 cosas con certeza, por eso es que les pedimos "una versión válida" y no "la versión válida". Si nada les permite tener 100% claro quien fue el culpable, la versión que generes debe cumplir con que no tenga contradicciones; el que hayan designado como culpable haya estado en el lugar del crimen antes del descubrimiento; los presuntos inocentes no mientan, etc.
