### ISSUE TITLE
[T1] DCCajas - Posición del robot al tomar una caja

### ISSUE THREAD

**Issue by edovt** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#16]
Hola!

Con respecto a la forma que el robot toma la caja, ¿La caja pasa al lugar del robot, o el robot pasa al lugar de la caja?. Por ejemplo, si tengo [(R), (C)], con R el robot, C la caja y () una posición, entonces no sé si queda [(R, C), ()] (como si el robot se echara al hombro la caja, sin moverse), o [(), (R, C)].

Saludos

**Comment by FeBalla** [comment]
Al siguiente instante de tiempo de ser tomada, la caja debería pasar a estar en la misma posición que el robot (ojo con el Z eso sí).
