### ISSUE TITLE
Archivo de Python para el visualizador

### ISSUE THREAD

**Issue by juanfra111** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#17]
Hola! La verdad no tengo ni idea como correr el código de la parte 3, no se como el clingo relacionarlo con el html por si alguien me puede ayudar, gracias.

**Comment by FeBalla** [comment]
Supongamos que tienes Windows, tu programa está en el archivo `model.lp` y quieres resolver el problema que está en `prob1.lp`. Puedes guardar el _output_ de tu programa en un archivo `output.txt` de la siguiente forma:
```
clingo -c bound=<un valor> model.lp prob1.lp > output.txt
```

Este _output_ que guardaste en tu archivo TXT es el que debes procesar con un programa en Python para que te quede en otro archivo de texto, digamos `parsed.txt`, con el formato descrito en el enunciado. Este archivo `parsed.txt` es el que puedes poner en el HTML para visualizar tu respuesta.

**Nota:** Si quieres probar, puedes crear a mano tus propios archivos de texto con el formato del enunciado y ponerlos en el visualizador para que veas cómo funciona 😄

**Comment by fran-gl** [comment]
Hola! ¿Es válido hacer un programa de python que escriba un archivo .txt, pero que se le pase directamente el output de clingo? Es decir, que para ejecutarlo haya que hacer lo siguiente
```clingo -c bound=<valor>  model.lp prob.lp | python3 process.py```

Gracias de antemano.

**Comment by fran-gl** [comment]
> Supongamos que tienes Windows, tu programa está en el archivo `model.lp` y quieres resolver el problema que está en `prob1.lp`. Puedes guardar el _output_ de tu programa en un archivo `output.txt` de la siguiente forma:
> 
> ```
> clingo -c bound=<un valor> model.lp prob1.lp > output.txt
> ```
> 
> Este _output_ que guardaste en tu archivo TXT es el que debes procesar con un programa en Python para que te quede en otro archivo de texto, digamos `parsed.txt`, con el formato descrito en el enunciado. Este archivo `parsed.txt` es el que puedes poner en el HTML para visualizar tu respuesta.
> 
> **Nota:** Si quieres probar, puedes crear a mano tus propios archivos de texto con el formato del enunciado y ponerlos en el visualizador para que veas cómo funciona 😄

Hola! ¿Es válido hacer un programa de python que escriba un archivo .txt, pero que se le pase directamente el output de clingo? Es decir, que para ejecutarlo haya que hacer lo siguiente
```clingo -c bound=<valor> model.lp prob.lp | python3 process.py```

Gracias de antemano.

**Comment by FeBalla** [comment]
> Hola! ¿Es válido hacer un programa de python que escriba un archivo .txt, pero que se le pase directamente el output de clingo? Es decir, que para ejecutarlo haya que hacer lo siguiente `clingo -c bound=<valor> model.lp prob.lp | python3 process.py`
> 
> Gracias de antemano.

El programa en Python no se evalúa, pero **sí es requisito**, así que mientras funcione, es válido, es decir, necesitamos que de alguna forma generen archivos de texto como los mostrados en el enunciado. Eso sí, deben dejar perfectamente claro en el README cómo es que funciona

**Comment by fran-gl** [comment]
Oka, gracias!
