### ISSUE TITLE
[DCCajas]: Cajas en en el suelo en Estanterias

### ISSUE THREAD

**Issue by mc-cari** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#18]
Hola, en el T final, las cajas tienen que estar sobre robots en las estanterías para que sea valido? O sea no se puede considerar que una caja esta en la posición de una estantería si esta en el suelo sin un robot?

**Comment by FeBalla** [comment]
Eso solamente aplica para el bonus, donde los robots deben ser capaces de tomar y soltar cajas. Para el ejercicio base, basta con que tomen la caja y lleguen a la estantería

**Comment by mc-cari** [comment]
Entonces en el bonus es valido dejar las cajas en la estantería, pero en el suelo, o solo es necesario que las cajas estén sobre robots en estanterías?

**Comment by FeBalla** [comment]
En el bonus, las cajas deben quedar sí o sí en las estanterías en el suelo. En la versión normal, basta con que el robot llegue con la caja encima a la meta.

**Comment by mc-cari** [comment]
Ya gracias
