### ISSUE TITLE
[DCClue] Duda sobre descubrimiento y mentiras

### ISSUE THREAD

**Issue by ShescBlank** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#19]
Hola :D

Tengo dos preguntas sobre detalles del enunciado:

1) Para el descubrimiento(X,T), se debe hacer que alguien esté en lugar X en el tiempo T para simular que fue esa persona quien descubrió el crimen o se asume que pudo haber sido alguien externo a las personas del problema?

2) Está claro que el culpable puede o no mentir, ya sea porque no dice nada o dice algo que no es contradictorio. En el caso que el culpable afirme varias cosas, en las que casi todas pueden ser verdad y una es contradictoria (entonces miente), debo hacer que mi modelo válido considere sus afirmaciones verdaderas y no la falsa, o simplemente, como ya mintió, todo lo que dijo es falso? Básicamente lo que estoy preguntando es que, si una persona miente, se asume que todo lo que dice puede ser falso o se considera verdadero lo que sí puede ser verdadero?

Muchas gracias de antemano y les deseo un muy buen fin de semana largo 😄

**Comment by FeBalla** [comment]
1. Es necesario que tengan claro que **todas las personas deben tener asignado un lugar para cada instante de tiempo**, ya que lo que se busca es que den una versión válida de cómo ocurrieron los hechos. Respecto a si debe haber alguien en el lugar de descubrimiento y en el tiempo de descubrimiento, no es realmente necesario, ya que no lo exigimos de forma clara en el enunciado. Podrían asumir que llegó un comunicado al curso o algo por el estilo jaja.
2. No necesariamente todo lo que dice es falso, ya que sería un problema bastante más complejo. Esto se traduce en que, si alguien miente, aunque sea 1 vez, es el culpable.

Buen fin de semana largo para ti también!

**Comment by aalmuna** [comment]
Gracias por la respuesta!

1) Perfecto, si fue algo que se me ocurrió muy de la nada y quería confirmar si era necesario. Me parece lo del comunicado jajaja
2) Entiendo que si alguien dice algo que no hace sentido, entonces miente y directamente es el culpable, además de que si dijo varias cosas no necesariamente todo es mentira. Mi duda es más a la hora de generar el modelo válido. Por ejemplo: si una persona dice 6 afirmaciones, 3 verdades y 3 mentiras, en el modelo válido debo considerar las 3 verdades o, como mintió, ya no es de confianza y no consideramos ninguna de sus afirmaciones?

Muchas gracias de nuevo :D

EDIT: Lo pregunto porque siento que es más fácil lo segundo que lo primero, aunque sigo pensando en la otra implementación.

**Comment by FeBalla** [comment]
En el modelo solo deben aparecer las situaciones que puedas tener 100% de certeza de que sean ciertas, independientemente de si provengan de una afirmación del culpable o de un presunto inocente.
