### ISSUE TITLE
Duda sobre condiciones de culpabilidad

### ISSUE THREAD

**Issue by Pabloski100** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#2]
Hola, me surgio una duda respecto a las condiciones de culpabilidad del enunciado en relacion al ejemplo del archivo prob1.lp. Habia entendido que el culpable era quien miente y estuvo en el lugar de descubimiento, pero, en prob1.lp se dice que el culpable es nico solo por haber mentido (o al menos, no veo manera de verificar de forma certera que estuvo en el lugar tambien).

¿Seria mejor interpretar la culpabilidad como "miente y es plausible que la persona estuviera en el lugar" o hay algo que no entendi?

**Comment by FeBalla** [comment]
La única forma que tienen de determinar quién miente es a partir de las afirmaciones o conocimientos que tienen, buscando contradicciones o cosas que no sean posibles. Por una cosa de lógica, el culpable tiene que haber estado **sí o sí** en el lugar del crimen antes del tiempo de descubrimiento, pero **no necesariamente deben saber con certeza en qué instante específico**.

Por eso es que les pedimos "una versión válida" y no "la versión válida". Esto significa que, en su _output_, el culpable debe haber estado en el lugar del crimen antes del descubrimiento, pero con la información que tienen **podría haber más de una posibilidad** (ej: haber estado en el tiempo t o en t').

> ¿Seria mejor interpretar la culpabilidad como "miente y es plausible que la persona estuviera en el lugar" o hay algo que no entendi?

Sí, debería ser más o menos equivalente a lo que digo al inicio de esta respuesta. Espero quede más claro 😄
