### ISSUE TITLE
[T1] PDF DCCajas

### ISSUE THREAD

**Issue by fran-gl** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#20]
Hola! Tengo una duda acerca del PDF que se pide en la Actividad 2 de la parte DDCajas de la T1. ¿Tenemos que explicar nuestro planteamiento de la parte de la Actividad 2 solamente (solo lo de robots procrastinadores), o también hay que incluir el de la Actividad 1 (todo lo de los robots)?

Gracias de antemano.

**Comment by FeBalla** [comment]
Solamente la parte de los robots procrastinadores. De todos modos, es muy útil y se valora que expliquen lo máximo posible, ya que facilita enormemente la corrección, sobre todo cuando hay errores.

**Comment by fran-gl** [comment]
Oka, gracias!
