### ISSUE TITLE
[T1] Opción de tomar cajas de los robots

### ISSUE THREAD

**Issue by fvaldes17** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#21]
Hola! ¿los robots siempre deben tomar una caja si ella está adyacente? Todo considerando las condiciones que tienen los robots al tomar la caja y las condiciones de la caja. En tal caso, ¿no podría pasar que un robot no tenga una caja, tenga una caja al lado y decida no tomarla por algún motivo (por ejemplo, de optimización)?
Muchas gracias!

**Comment by FeBalla** [comment]
La regla es que un robot solamente puede tomar una caja si esta está adyacente y en el suelo, pero **no está obligado a tomarla**. De hecho, esto en muchos casos sería derechamente imposible, ya que si un robot tiene, por ejemplo, 2 cajas adyacentes, sí o sí no podría tomar 1 de ellas, aunque quisiera.
