### ISSUE TITLE
[DCCajas] Programa Python

### ISSUE THREAD

**Issue by ghost** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#22]
Hola, en el programa de Python tenemos que generar un archivo .txt por cada modelo? Y es posible basarnos en el archivo process.py de las ayudantías para hacerlo?

**Comment by FeBalla** [comment]
El archivo de Python debe ser capaz de procesar el _output_ para cualquier instancia del problema (no solo las de ejemplo) y dejarlo en un archivo de texto con el formato mostrado en el enunciado. 

El cómo funcione este script es totalmente a decisión suya, ya que no se evalúa, pero sí es requisito para poder revisar su tarea de forma independiente a la modelación personal. Eso sí, deben explicar en el README para que podamos replicar lo que hacen ustedes.
