### ISSUE TITLE
[DCClue] Versiones contradictorias

### ISSUE THREAD

**Issue by nicolecll** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#23]
Hola, no me queda claro como manejar el caso en que dos personas (X, Y) dan una versión distinta de los hechos pero no hay una tercera (Z) que corrobore la versión de X o de Y, en este caso, ¿se asumen que ambos mienten? ¿ninguno miente?.

De antemano muchas gracias!

**Comment by FeBalla** [comment]
En este caso, a partir solo de esa información, no tienes cómo asegurar nada, por lo que pasaría a ser información irrelevante. Eso sí, evaluar que no se contradiga con cosas que sabemos que son ciertas o ese tipo de situaciones.
