### ISSUE TITLE
Duda Cajas - DCCajas

### ISSUE THREAD

**Issue by anais-mv** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#24]
Hola! el robot sólo puede tomar la caja estando ya en el espacio de la caja? o si el robot está atrás de la caja por ejemplo la puede tomar y ahora la caja está en la misma posición que el robot? (en este caso Y-1)

**Comment by anais-mv** [comment]
Entiendo que solo puede tomar la caja estando adyacente pero no entiendo si en el momento en que la toma el robot ahora está donde estaba la caja o la caja está donde estaba el robot, en resumen, se mueve la caja o se mueve el robot?

**Comment by FeBalla** [comment]
Cuando un robot toma una caja, **la caja pasa a estar en la misma posición del robot** que la tomó al tiempo siguiente (y con un Z=1). Es importante que sea al tiempo siguiente porque si pasa a ser en el mismo instante, esta caja estaría duplicándose y estando en 2 lugares a la vez.
