### ISSUE TITLE
Duda robots procastinadores

### ISSUE THREAD

**Issue by BrunoFarfan** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#25]
Quería saber si en esa parte de la tarea lo que hay que optimizar es la cantidad de movimientos que hacen los robots, o también lo rápido que llegan al objetivo? Es decir, hay que preocuparnos de que no hagan movimientos inútiles, o que lleguen lo más rápido posible, y una vez que lo hacen, que no se muevan de su lugar?

**Comment by FeBalla** [comment]
La pregunta es un poco ambigua, pero intentaré ser lo más claro posible:
* Todos sus modelos deben poder ser resueltos en el mínimo tiempo posible. Sin embargo, para esto no les exigimos que lo hagan desde el mismo modelo, sino que pueden cambiar el valor de la constante de tiempo máximo `bound` (visto en ayudantías) hasta la mínima posible para que haya solución. Por eso en los archivos de ejemplo hay comentarios como _"se puede resolver con bound=3"_
* El hecho de que se resuelva en el mínimo tiempo según el valor de `bound` no implica que robots que puedan llegar a una estantería en menos tiempo efectivamente lo hagan, esto es lo que se señala en el enunciado sobre los robots procrastinadores. Recomiendo ver el ejemplo.
* En la pregunta de los robots procrastinadores lo que se busca es que robots no hagan movimientos inútiles, lo que implica que si llegan a una estantería y se pueden quedar ahí, entonces lo hagan.

En resumen: el resolver el problema con el mínimo tiempo posible se hace a través de ir bajando el valor de la constante `bound`, mientras que para los robots procrastinadores buscamos optimizar el problema para que los robots no hagan movimientos inútiles y, una vez en la estantería, se queden ahí siempre y cuando sea posible.

**Comment by j4vito** [comment]
Creo que a lo que se refiere Bruno, es que tal vez los robots hagan movimientos inútiles antes de llegar a la estantería (van sin apuro pues esperan a sus compañeros). Tengo entendido que esto no hay que optimizarlo pues solo nos ineteresa que se queden en posición al haber llegado a la estantería. Es así?

**Comment by FeBalla** [comment]
> Creo que a lo que se refiere Bruno, es que tal vez los robots hagan movimientos inútiles antes de llegar a la estantería (van sin apuro pues esperan a sus compañeros). Tengo entendido que esto no hay que optimizarlo pues solo nos ineteresa que se queden en posición al haber llegado a la estantería. Es así?

Lo que pasa es que debería ser equivalente, porque la idea es que lleguen a la meta y se mantengan ahí lo máximo posible hasta el final. Porque si, por ejemplo, quieres optimizar que el robot se quede hasta el final el mayor tiempo posible, entonces un problema dual sería que llegue lo antes posible para estar más tiempo ahí.

Eso sí, como pista les puedo decir que la optimización esperada no es exactamente estar el mayor tiempo posible en una estantería, sino que estar el mayor tiempo en la estantería sin moverse hasta el final del tiempo de evaluación, por eso se recomienda ver el problema de optimización desde el final hacia atrás 👀
