### ISSUE TITLE
[DCClue] - Definición de sospechoso

### ISSUE THREAD

**Issue by fguinez** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#26]
En el enunciado se define sospechoso como:
> Los sospechosos son presuntos inocentes, pero que además han estado al menos 3 veces en el lugar del crimen antes del tiempo de descubrimiento.

Esto me deja la duda de si la persona culpable puede ser también sospechosa. Esto entendiendo que el culpable puede haber estado o no 3 3 o más veces en el lugar del crimen, pero no sé si la afirmación _"son presuntos inocentes"_ lo excluye de la posibilidad de ser sospechoso a la vez de culpable.

En otras palabras, ¿se puede ser sospechoso y culpable a la vez?

**Comment by FeBalla** [comment]
Un **culpable no puede ser sospechoso** porque tiene una condición que se lo impide, esto es, _"los sospechosos deben ser presuntamente inocentes"_ (y el culpable claramente no es un presunto inocente)-
