### ISSUE TITLE
[DCCajas] - Organización entregables

### ISSUE THREAD

**Issue by fguinez** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#27]
Estoy un poco confundido con la forma en que debemos organizar los diferentes entregables de DCCajas. ¿Un directorio como el siguiente sería correcto?
```
02 - DCCajas
 |___ actividad1.lp
 |___ actividad2.lp
 |___ actividad2.pdf
 |___ bonus.lp
 |___ script.py
```

**Comment by FeBalla** [comment]
Sí, esta perfecto. Lo más importante es que puedan dejar un README o algo del estilo que explique que es cada archivo, así evitamos confusiones. En cuanto al PDF, puede ser el mismo que esté en el directorio base. Ambas opciones son válidas siempre y cuando quede claro.

**Comment by fguinez** [comment]
Gracias!
