### ISSUE TITLE
DCClue incongruencia entre dos personas

### ISSUE THREAD

**Issue by DonMarto** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#28]
Hola!
Tengo una duda con un caso borde del problema. Que ocurre en el caso de que P1 afirme algo contradictorio a P2, pero no haya forma de saber quien miente? Es decir, si se contradicen, uno de los dos debe mentir, y por ende ser culpable. Sin embargo, en este caso, asumamos que no se sabe la posición (ni se puede inferir), de P1 ni de P2 en ningún momento y es lo único que dicen (es decir, no se contradicen con nadie más). En este caso no se puede saber quien es el culpable (a ciencia cierta), y por ende no se puede saber que información es verídica, para ponerla de restricción en el modelo.

Por ejemplo, digamos que lo único (aparte de la construcción del mapa y personas) en el código es:
- afirmacionLugar(P1, P, L1, T).
- afirmacionLugar(P2, P, L2, T).
Tal que P1 != P2, y L1 != P2, y no se sabe nada más.
En este caso, para nuestro modelo, la unica información que se tiene, es que P debe estar en L1 o L2, en el tiempo T, pero no se puede determinar cual, y no sabría taclear este caso.

Creo que esta duda se mencionó en el issue #23, pero la respuesta no responde a la mía, así que decidí preguntarlo. 
Gracias de antemano.

**Comment by FeBalla** [comment]
Hola!
En ese caso, si ambos dicen una versión que es contradictoria, entonces sí o sí uno de los dos debe ser el culpable. Sin embargo, no puedes saber con certeza, al menos con esa información, cuál de las dos personas es la culpable. Dicho esto, en todos los modelos que tenga tu programa, al menos uno de los dos debería ser culpable (digo al menos porque podrían haber más contradicciones del estilo).

Recuerden que les pedimos "una versión válida" y no "la versión válida". Lo importante, es que sus modelos **sean consistentes**, es decir, no tengan ninguna contradicción, ya que, valga la redundancia, dejarían de ser versiones válidas.
