### ISSUE TITLE
[DCClue] Duda sobre mentiras del culpable

### ISSUE THREAD

**Issue by benjamincaro** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#29]
Hola, tengo una duda similar a la 2 de la issue #19, no me quedó clara la respuesta que se dio ahí.
En el caso que en el problema entregado se de que
`afirmacionLugar(P1, P1, metro, 1).` 
`afirmacionLugar(P1, P3, cai, 2).` 
`afirmacionLugar(P2, P1, cai, 1).`
`afirmacionLugar(P3, P1, cai, 1).`  
Entonces la persona `P1` sería culpable al contradecirse porque, según `P2` y `P3`, `P1` se encontraba en otro lugar en el tiempo `1` y
`afirmacionLugar(P1, P1, metro, 1).` sería falsa.
Mi pregunta es qué pasaría con la afirmación `afirmacionLugar(P1, P3, cai, 2).` si no se contradice con otras afirmaciones. 
¿Generará `personaEnLugar(P3, cai, 2).` o se puede descartar al saber que viene del culpable?

**Comment by FeBalla** [comment]
Buena pregunta!
En ese caso, tal como señalé en #19, no podrías saber si `afirmacionLugar(P1, P3, cai, 2).` es cierta o no, lo que en resumidas cuentas se traduce en que es información irrelevante. Esto significa que P3 podría estar en el CAi en el tiempo 2 o también podría no estar. Tu versión seguiría siendo válida en ambos casos, ya que no genera ninguna contradicción porque no tienes certeza respecto a esa información.

**Comment by benjamincaro** [comment]
muchas gracias!
