### ISSUE TITLE
[T1] Duda sobre personaEnLugar

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#3]
Hola, tenía la duda de si las personas pueden optar por no cambiar de posición de un tiempo a otro. Gracias.

**Comment by FeBalla** [comment]
Sí se puede mantener en su lugar. En la sección del mapa se explica más claramente:
> **NOTA:** Considera que el grafo es no dirigido, por lo que se puede recorrer en ambas direcciones. Por otra parte, ten en cuenta que un lugar siempre estará conectado consigo mismo.
