### ISSUE TITLE
[T1] [minimize, maximize]

### ISSUE THREAD

**Issue by j4vito** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#30]
Hola! Estoy intentando maximizar la ocrrencia de un átomo en particular, en particular tengo la regla <x(t) :- algo(t)> y quiero que en mi modelo aparezca el máximo número posible de x(t).

Intenté: #maximize {x}. Dado que así se indica que se hace en la guía de clingo pero esto me retorna "info: tuple ignored: -x@0"

**Comment by FeBalla** [comment]
Hola!
El uso de `#maximize` y `#minimize` es algo que se espera que investiguen por su cuenta y se encuentra explicado en la guía de Clingo que envié en el anuncio con material de apoyo para la tarea. De todos modos, por lo que puedo suponer por el error es que la sintáxis del `#maximize` no está del todo correcta, ya que ni siquiera se le está entregando el predicado con su variable.

Ahora, una **pista importante** que les puedo dar es que en la misma guía se explican 2 usos de estos predicados:
1. Maximizar/minimizar la cantidad de ocurrencias de un predicado en el modelo, es decir, que aparezca más (o menos) veces un cierto predicado (independiente de los valores que puedan tomar sus variables).
2. Maximizar/minimizar el valor de un predicado del modelo, por ejemplo, si tenemos `ganancias(G)`, sería optimizar el valor de _G_.

Ambos le pueden servir según cómo modelen su problema. En la guía también se muestran ejemplos de la sintáxis de ests funciones. Espero te sirva y lamento no poder dar mayor información 😅
