### ISSUE TITLE
[DCClue] Solicitud de más ejemplos para testear

### ISSUE THREAD

**Issue by Agustinuv** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#32]
Hola, será posible que nos den más casos para probar nuestros programas en DCClue? Un segundo mapa o casos con un poco más de dificultad para así encontrar posibles errores que no se logran ver con los casos actuales nos ayudaría mucho :)

**Comment by FeBalla** [comment]
Hola!
Por ahora no nos podemos comprometer con más ejemplos porque el cuerpo de ayudantes también está bien ocupado con evaluaciones (me incluyo) 😢 . Sin embargo, la idea de los problemas de ejemplo es que les sirva para poder crear casos propios. La complejidad de los casos que usaremos nosotros no serán mucho mayor que los mostrados, no hay intención de perjudicarlos, solamente procuren que la detección de los culpables y la consistencia de la versión sea precisa.

**Comment by FeBalla** [comment]
@Agustinuv 
Para poder llegar a un punto medio respecto a su solicitud, permitiremos que pongan ejemplos de problemas/mapas **únicamente en esta _issue_**. La idea es que sigan el siguiente formato:
```
% Problema
predicado1
predicado2
predicado3
% El culpable debe ser: <culpable1>, (y más posibles culpables si hubieran varios modelos)
```
Y para el caso de los mapas:
```
%Mapa
predicado1
predicado2
```
Nosotros intentaremos ir verificando que sus propuestas sean correctas y reaccionaremos con un 👍 cuando esté bien y con 👎  si es que está mal. No podemos asegurar respuestas muy rápidas, pero haremos un intento, así que también actúen con moderación.

**Comment by Agustinuv** [comment]
Hola, tengo este ejemplo :)


culpable(nico)
sospechoso(fernando)

```% problema
tiempo(1..5).

persona(nacho).
persona(nico).
persona(fernando).


personaEnLugar(nacho, metro, 1).
personaEnLugar(nacho, cai, 4).

personaEnLugar(fernando, carritos, 1).
personaEnLugar(fernando, carritos, 2).

afirmacionLugar(nacho, fernando, carritos, 3).
afirmacionLugar(nico, fernando, dcc, 3).

descubrimiento(carritos, 5).

%mapa
lugar(cai).
lugar(metro).
lugar(dcc).

lugar(carritos).
lugar(entrada).



camino(dcc, cai).
camino(metro, carritos).
camino(metro, entrada). 
camino(carritos, entrada).
camino(entrada, dcc).

**Comment by fvaldes17** [comment]
Hola, se me ocurrió este ejemplo:

culpable(ibai)
no hay sospechosos. 

```
% Problema
tiempo(1..6).

persona(ibai).
persona(messi).
persona(cr7).

personaEnLugar(ibai, espana, 6).
personaEnLugar(ibai, espana, 4).
personaEnLugar(ibai, espana, 3).
personaEnLugar(ibai, espana, 2).
personaEnLugar(ibai, espana, 1).

personaEnLugar(messi, andorra, 6).
personaEnLugar(messi, andorra, 4).
personaEnLugar(messi, andorra, 3).
personaEnLugar(messi, andorra, 2).
personaEnLugar(messi, andorra, 1).

personaEnLugar(cr7, francia, 6).
personaEnLugar(cr7, alemania, 3).
personaEnLugar(cr7, alemania, 2).

afirmacionLugar(ibai, cr7, alemania, 1).
afirmacionLugar(cr7, cr7, alemania, 1).

descubrimiento(portugal, 5).

% Mapa:
lugar(andorra).
lugar(francia).
lugar(espana).
lugar(portugal).
lugar(alemania).

camino(portugal, espana).
camino(espana,andorra).
camino(andorra,francia).
camino(espana,francia).
camino(francia, alemania).
```

**Comment by FeBalla** [comment]
> Hola, se me ocurrió este ejemplo:
> 
> culpable(ibai) no hay sospechosos.
> 
> ```
> % Problema
> tiempo(1..6).
> 
> persona(ibai).
> persona(messi).
> persona(cr7).
> 
> personaEnLugar(ibai, espana, 6).
> personaEnLugar(ibai, espana, 4).
> personaEnLugar(ibai, espana, 3).
> personaEnLugar(ibai, espana, 2).
> personaEnLugar(ibai, espana, 1).
> 
> personaEnLugar(messi, andorra, 6).
> personaEnLugar(messi, andorra, 4).
> personaEnLugar(messi, andorra, 3).
> personaEnLugar(messi, andorra, 2).
> personaEnLugar(messi, andorra, 1).
> 
> personaEnLugar(cr7, francia, 6).
> personaEnLugar(cr7, alemania, 3).
> personaEnLugar(cr7, alemania, 2).
> 
> afirmacionLugar(ibai, cr7, alemania, 1).
> afirmacionLugar(cr7, cr7, alemania, 1).
> 
> descubrimiento(portugal, 5).
> 
> % Mapa:
> lugar(andorra).
> lugar(francia).
> lugar(espana).
> lugar(portugal).
> lugar(alemania).
> 
> camino(portugal, espana).
> camino(espana,andorra).
> camino(andorra,francia).
> camino(espana,francia).
> camino(francia, alemania).
> ```
@fvaldes17 
En este caso hay un pequeño problema y es que si Ibai está en todos los tiempos t, tales que t < 5 en España y el descubrimiento es en el tiempo 5 en Portugal, entonces Ibai no puede haber sido porque nunca estuvo en Portugal antes del descubrimiento. Recuerda que debe haber estado antes del descubrimiento en el lugar del crimen, sin incluir el tiempo de descubrimiento mismo.
