### ISSUE TITLE
[DCCajas] - Procrastinadores sin objetivo

### ISSUE THREAD

**Issue by fguinez** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#33]
La actividad 2 es explícita en torno a que los robots no procrastinen una vez que lleguen con la caja a su objetivo. Sin embargo, ¿qué pasa en problemas con más robots que cajas?

En estos casos puede darse que algunos de los robots no son necesarios en lo absoluto para llevar alguna de las cajas, por lo que podrían realizar movimientos inútiles sin entrar en lo descrito como procrastinación robótica.

¿Debemos intentar optimizar estos casos también? ¿O solo nos importa que los robots que efectivamente llevan una caja a un objetivo presenten un comportamiento óptimo?

**Comment by vWing7** [comment]
Hola, es lo último que dices, lo que importa es que los robots que lleven una caja al objetivo presenten el comportamiento óptimo
