### ISSUE TITLE
[DCCajas] - Tiempos de ejecución

### ISSUE THREAD

**Issue by fguinez** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#34]
¿Debemos preocuparnos de mantener las ejecuciones dentro de algún límite de tiempo?

**Comment by vWing7** [comment]
Hola, no se tiene un límite especifico de ejecución así que mientras la espera sea razonable está bien. Si se llega a demorar mucho, es posible que nos haga pensar que simplemente no termina cuando estamos revisando.

**Comment by fguinez** [comment]
Super, gracias!
