### ISSUE TITLE
[DCCajas] Archivo de python en caso de UNSATISFIABLE

### ISSUE THREAD

**Issue by fran-gl** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#35]
Hola! Tengo una duda acerca del archivo de python de la parte de DCCajas de la T1. En caso de que el output del programa de clingo sea UNSATISFIABLE, por ejemplo por un valor de bound muy pequeño, ¿qué debería hacer el archivo de python? ¿O no es necesario manejar este caso?

Muchas gracias de antemano.

**Comment by vWing7** [comment]
Hola, no es necesario que manejen ese caso

**Comment by fran-gl** [comment]
Perfecto, gracias!
