### ISSUE TITLE
[DCCajas] Coordenadas de una caja tomada

### ISSUE THREAD

**Issue by Pabloski100** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#36]
Hola, me surgio una duda mientras avanzaba esta parte de la tarea, en una parte dicen "No puede haber más de 1 robot o caja en una celda en el mismo instante de tiempo.", pero, cuando un robot toma una caja ¿es valido interpretar que esta cargandola sobre si mismo? tipo, que compartan coordenadas mientras se mueven

**Comment by fguinez** [comment]
Preguntaron algo muy parecido en #8. Al final lo importante es considerar la coordenada Z, que cuando tomas una caja pasa a ser Z=1, pero los robots siempre se mantienen en Z=0. Eso implica que robot y caja no están exactamente en la misma celda, solo comparten X e Y.

Edit/Aclaración: No soy ayudante

**Comment by FeBalla** [comment]
> Hola, me surgio una duda mientras avanzaba esta parte de la tarea, en una parte dicen "No puede haber más de 1 robot o caja en una celda en el mismo instante de tiempo.", pero, cuando un robot toma una caja ¿es valido interpretar que esta cargandola sobre si mismo? tipo, que compartan coordenadas mientras se mueven

Lo que menciona @fguinez es totalmente correcto. Esto está en la issue #8, así que la marcaré como duplicada, pero en el fondo es eso: el Z indica si la caja está siendo transportada o no y, si está siendo transportada, entonces puede compartir la posición en X e Y con el robot que la lleva.
