### ISSUE TITLE
[DCCajas] Duda Bonus

### ISSUE THREAD

**Issue by mc-cari** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#37]
Hola, en el Bonus, los robots tienen que dejar las cajas en el suelo de la estantería, entonces hay robots procastinadores en este caso? Ya que los robots no llegan a una estantería, se espera que sea un archivo aparte al de robots procastinadores?

**Comment by FeBalla** [comment]
O sea, de todos modos podría haber robots procrastinadores, ya que mientras llevan una caja podrían ponerse a dar vueltas innecesarias. Sin embargo, como no fuimos tan explícitos en el enunciado, consideraremos para el bonus versiones con la optimización de la procrastinación y sin ella. Lo importante es que se pueda resolver con el mínimo `bound` y dejen las cajas en las estanterías.

**Comment by mc-cari** [comment]
Vale gracias
