### ISSUE TITLE
[T1] Repositorio de entrega

### ISSUE THREAD

**Issue by benjamincaro** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#39]
Hola! No me ha llegado ninguna invitación para ingresar al repositorio de entrega de la tarea. Revisé de nuevo el form de inicio de semestre de ingreso de usuario de github y lo contesté. Además, tengo entendido que se comunicaron con las personas que no habían contestado el form, así que no sé que pudo pasar. ¿A quién le escribo?

**Comment by FeBalla** [comment]
Hola!
No les va a llegar una invitación, sino que en el anuncio "Tarea 1 - Publicada" hay un enlace en el que tienen que entrar con su cuenta de GitHub y ahí se les creará un repositorio en la organización. Cualquier duda adicional puedes escribir a iic2613@ing.puc.cl

**Comment by benjamincaro** [comment]
uhh lo había pasado por alto. Gracias!
