### ISSUE TITLE
[T1] Duda sobre tiempo y personaEnLugar

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#4]
Hola, el primer segundo del programa debe ser el segundo 0 o 1? pregunto para saber si asignar un lugar a cada persona en el segundo 0.

**Comment by FeBalla** [comment]
En el caso de DCClue, **el tiempo parte desde 1** y pueden comprobarlo con las instancias de ejemplo que se les da en la carpeta `problems`
