### ISSUE TITLE
[DCClue] duda condiciones 1 y 3 de Presuntos Inocentes

### ISSUE THREAD

**Issue by Julius9** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#40]
Hola! tengo una duda sobre las condiciones 1 y 3, las cuales son:

(1) Como un presunto inocente no puede mentir, si dice que alguien estaba en un lugar en un tiempo determinado, entonces debe ser cierto y estar en ese lugar en dicho instante.
(3) Como un presunto inocente no puede mentir, no puede decir que alguien estaba en un lugar si sabemos de antemano que estaba en otro.

A mi juicio estas dos condiciones son idénticas y no se cumplen cuando el Presunto Inocente afirma que alguien estaba en L1, pero personaEnLugar dice que estaba en L2. ¿Estoy confundido o es justamente esto?

**Comment by FeBalla** [comment]
No son idénticas porque la primera hace referencia a que si alguien es presuntamente inocente, entonces todo lo que dice debe ser cierto (ya que no puede mentir). Por lo tanto, si P1 es inocente y dice que P2 estaba en L en el tiempo T, entonces en el modelo eso se debe cumplir.

Sin embargo, la otra regla hace referencia a que hay cosas que nosotros sabemos que son ciertas desde el inicio, por ejemplo, sabemos que P1 estaba en L en el tiempo T (porque la instancia lo decía). En ese caso, si P2 es presuntamente inocente, no puede decir algo que contradiga eso que es un hecho que sabemos con 100% de certeza.
