### ISSUE TITLE
[T1] Duda función maximize, manejo archivo python.

### ISSUE THREAD

**Issue by juanjouriarte** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#41]
Hola, la función maximize al utilizarla me arroja 3 modelos donde uno es el óptimo y los otros son soluciónes factibles pero no óptimas. ¿Como manejo ese caso para correr el archivo python? ¿Hay un commando de clingo para arrojar solo la solución optima?.

Pongo un ejemplo de como me arroja la solución, pondre numeros aleatorios pero que estan ordenados de mayor a menor:
```
Answer1:

Optimization: X  "Donde X es un numero"

Answer2:

Optimization: Y  "Donde Y es un numero, y es menor a X"

Answer3:

Optimization: Z  "Donde Z es un numero, y es menor a Y"

Models       : 3
Optimum    : yes
Optimization : Z
Calls        : 1
```
Donde claramente el optimo sería Z al ser el menor de todos, y además porque lo señala clingo pero no lo arroja solo en el output, lo que hace que process.py no lo pueda reconocer.

**Comment by FeBalla** [comment]
Al usar funciones de optimización en Clingo, el programa va iterando hasta encontrar el óptimo, por lo que el último modelo es el que va a ser óptimo y ese es el que deberías extraer con el script en Python.

**Comment by juanjouriarte** [comment]
Muchas gracias!
