### ISSUE TITLE
Pregunta 3 - Test Formativo: Propiedades de Heurísticas, Minimax 

### ISSUE THREAD

**Issue by fguinez** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#42]
Hola!

Creo que algo faltó en el enunciado de la pregunta 3 del último test formativo. Se presenta un árbol que parte en el nodo A y hay una casilla que rellenar, pero no se realiza ninguna pregunta al respecto.

En mi caso respondí 2 pensando que se buscaba el valor obtenido al ejecutar Minimax desde A. Sin embargo, me produce curiosidad saber cuál era la pregunta real como para que la respuesta correcta sea 0.

![Screen Shot 2022-05-09 at 18 01 27](https://user-images.githubusercontent.com/26127246/167506440-b00620f4-8403-44e7-aaad-7ff2f4e6980a.png)

**Comment by FeBalla** [comment]
No se me ha pasado el mensaje por si acaso, estoy consultando con el profesor Jorge, ya que los test formativos no los revisamos nosotros 😅

**Comment by FeBalla** [comment]
No sé si a esta altura tiene sentido mantener esta _issue_ abierta jaja el profe nunca me respondió y yo creo que ya no recuerda 🚀

**Comment by fguinez** [comment]
Está bien jaja, gracias por la preocupación!
