### ISSUE TITLE
Control 6 - Error pregunta 6

### ISSUE THREAD

**Issue by fguinez** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#44]
Hola! Dado que ya no tendremos clases con el profesor Baier, vengo con otra duda relacionada a controles 😅

Creo que la respuesta correcta a esta pregunta era 14 y no 15.

Si miramos los primeros nodos, tenemos que:
- El camino `A -> B -> C` tiene costo 5
- El camino `A -> C` tiene costo 6

Por lo tanto, a diferencia del camino verde marcado, realmente el óptimo pasa por `B` y tiene un costo menor en una unidad al camino verde. Esto implica que nuestro `g(K) = 13` y `h(K) = 1`, luego `f(K) = g(K)+h(K) = 14`.

Saludos!

![Screen Shot 2022-05-10 at 00 11 11](https://user-images.githubusercontent.com/26127246/167743509-80b79ce3-e9e8-4727-ada6-3c475b158f8d.png)

**Comment by FeBalla** [comment]
Efectivamente, **hay un error**. Lo que sucede es que lo que nosotros mencionamos como el camino óptimo realmente no lo era, pero no fue un distractor, sino una equivocación por parte nuestra. 

Si asumías que lo que decíamos nosotros era cierto, la respuesta era 15, pero si lo hacías desde el inicio, encontrando el verdadero camino óptimo, la respuesta era 14. Veremos qué hacer con la pregunta: si eliminarla o dejar ambas correctas. En cualquier caso, **muy buena observación** y muchas gracias por la corrección 👍

**Comment by FeBalla** [comment]
Consideraremos **ambas alternativas** como correctas 😄
