### ISSUE TITLE
T1 - Casos de prueba para recorrección

### ISSUE THREAD

**Issue by fguinez** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#45]
Hola de nuevo!

¿Hay posibilidad de que suban los casos utilizados para corregir la tarea 1? ¿o se corrigió con los mismos problemas que venían en el repo base? 

Siento que parte de mi feedback no se condice con lo que había testeado por mi cuenta, pero no se bien cómo corroborarlo sin tener los mismos testcases que se usaron en la corrección.

_PD: Lo 100to @FeBalla, te he llenado de issues hoy 👉👈_

**Comment by FeBalla** [comment]
Subí algunos casos evaluados al Syllabus. No los podemos subir todos porque hay muchos aspectos de la pauta que se manejan a nivel interno, considerando la continuidad del curso. No obstante, con esos se deberían poder hacer una idea.

Ojo que varias tareas tuvieron descuentos o no se les consideró puntaje en algunas partes porque no tenían ningún README que explicara cómo se ejecutaban sus programas.

Espero esto les sirva un poco para aclarar sus dudas!

**Comment by fguinez** [comment]
Muchas gracias!
