### ISSUE TITLE
T2 - Binary Heap

### ISSUE THREAD

**Issue by BrunoFarfan** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#46]
Hola!

Estoy leyendo el archivo de `binary_heap.py`, pero me está costando entender que hacen sus diferentes métodos. No sé si podrían dar alguna explicación resumida de qué hace cada uno, o si pueden pasar algún link o material que podamos usar para comprenderlo mejor.
Gracias!

**Comment by CataAlamos** [comment]
Hola! Espero que estes bien, Binary Heap es una estructura de datos que permite de guardar datos de una forma especial. El nodo raíz, al menos para min heap es el nodo con el valor más pequeño y los nodos hoja son los más grandes. Esta es usada para poder mantener las propiedades asociadas a las lista open. Para más información te voy a dejar un link a un [video](https://www.youtube.com/watch?v=t0Cq6tVNRBA). 
Espero que te sirva
