### ISSUE TITLE
[T2] [DCCubo Rubik] Formato solución A*

### ISSUE THREAD

**Issue by fran-gl** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#47]
Hola! No me queda claro cuál es el formato que debe tener la solución de A* en la actividad 1 de DCCubo Rubik (```sol``` en  ```sol, exp, tim = astar.search()```), para que después quede escrito correctamente en ```parsed.txt```. Si es posible, ¿lo podrían explicar?

Muchas gracias de antemano.

**Comment by SugarFreeManatee** [comment]
Hola! El formato queda a tu criterio, aunque para la tarea recomendamos mantenerlo (Solución, expansiones, tiempo) por las preguntas que se hacen. Con respecto al visualizador, sol se refiere al trace del nodo final de la solución encontrada. Esto es un string que representa como se llegó a ese nodo. El método que lo genera se encuentra en el módulo node.py

**Comment by fran-gl** [comment]
Okaa, gracias!
