### ISSUE TITLE
DCConecta-4 - Puntaje por pregunta y estructura board

### ISSUE THREAD

**Issue by APeraltaS16** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#48]
Hola!
Para la actividad 2 de DCConecta-4 cual es el formato de "board" que se le entrega a las funciones two_next_to(board, player token) y three_next_to(board, player token). 
Por otro lado sale que este item tiene un valor de 3 puntos pero las 3 actividades suman 2 (act1 0.5, act2 0.7, act3 0.8, sum act1+act2+acr3 = 2)

Saludos! :)

**Comment by FeBalla** [comment]
Hola, cuando tengan este tipo de dudas, idealmente pongan **títulos más explicativos** y, si se trata de dudas muy diferentes, hacerlas en 2 _issues_ diferentes.

Dicho esto, la estructura de `board` la pueden encontrar en donde se define la clase `DCConecta-4`, ahí pueden poner algún `print` o algo para entender la estructura. Parte del desafío es leer el código, entenderlo y asociarlo a lo visto en clases/ayudantías.

Respecto al puntaje, la versión del enunciado que subíamos tenía ese problema. Los puntajes reales que cambian son:

1. La actividad 3 de DCCubo Rubik tiene 1.5 pts. (0.5 más de lo que decía el enunciado)
2. La actividad 1 de DCConecta-4 tiene 0.7 pts. (0.2 más de lo que decía el enunciado)
3. La actividad 3 de DCConecta-4 tiene 1.1 pts. (0.3 más de lo que decía el enunciado)

De todos modos, ya subí al repositorio _template_ el enunciado con los puntajes actualizados y actualizaré el archivo que está en el anuncio de Canvas. Gracias por el comentario! 😄
