### ISSUE TITLE
DCConecta-4 - Duda comportamiento de la simulación de 100 juegos

### ISSUE THREAD

**Issue by ShescBlank** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#49]
Hola!

Estaba terminando de programar la pregunta del DCConecta-4 pero me pasó que, en la parte de simulación de los 100 juegos de la actividad 3, todos los tableros resultaron ser iguales, es decir, siempre ganaba el mismo jugador ya que siempre se hacían las mismas jugadas. Este comportamiento igual me hace sentido dado que no existe un componente aleatorio a la hora de elegir una jugada, considerando las funciones de evaluación de la actividad 2.

¿Me habré equivocado en alguna parte? Porque, si todos los juegos de la simulación son iguales, no tiene mucha gracia hacer una comparación de rendimiento de las dos funciones.  Quizás podría agregar que las primeras jugadas sean aleatorias con el objetivo de generar distintos tableros finales.

Muchas gracias!

**Comment by FeBalla** [comment]
Es extraño, ya que al momento de desempatar deberían haber diferencias. De todos modos, puedes darle un comportamiento aleatorio al inicio que obligue que los juegos no sean iguales. Por ejemplo, que no parta siempre el mismo jugador o que la primera ficha se juegue al azar.

**Comment by aalmuna** [comment]
Oh, puedo preguntar por qué debería haber diferencias al desempatar si hasta cierto punto se tiene el mismo tablero? Es que me llama la atención porque las funciones parecieran estar bien al revisar varios ejemplos y, si quito la poda alfa-beta, el resultado se mantiene igual solo que lo calcula más lento.

De igual manera, aplicaré los comportamientos aleatorios que mencionas. Muchas gracias por la respuesta!

**Comment by fran-gl** [comment]
> que la primera ficha se juegue al azar.

Hola! La primera ficha al azar sería la primera ficha del primer jugador solamente? O puede ser la primera ficha de cada jugador? (Con la primera opción no obtengo juegos diferentes, con la segunda sí).

Gracias de antemano.

**Comment by CataAlamos** [comment]
Hola!  Ambos deben ser a la azar, en su primera movida. Eso debería genera distintos juegos.

**Comment by fran-gl** [comment]
Perfecto, muchas gracias!
