### ISSUE TITLE
[T1] Desarrollo de la tarea

### ISSUE THREAD

**Issue by sh1njr** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#5]
Mi duda es acerca de dónde debo desarrollar el código de la pregunta 2 (DCClue) de la tarea. Esto también se relaciona con cómo se corregirá.

La primera opción puede ser desarrollar el código en un archivo tipo _main.lp_ y luego ejecutarlo con archivos con instancias (similares a prob.lp) que en conjunto con este _main.lp_ y el archivo de mapa tengan el output deseado.

La otra opción sería escribir un solo archivo con todo incluido. Sin embargo, esta opción no me parece la más óptima para la corrección de la tarea ya que se hace más difícil probar otras instancias.

Me aseguré de ver todas las partes del enunciado y creo que no estaba esta aclaración :(  

Gracias!

**Comment by vWing7** [comment]
Hola, debes desarrollarlo de la primera forma que dices, es decir un archivo base con la lógica (main.lp en tu caso), con archivos aparte para instancias.

Saludos.
