### ISSUE TITLE
DCCubo Rubik - Tiempos de ejecución ejemplos

### ISSUE THREAD

**Issue by ceosorio** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#50]
Hola! 
Estoy intentando correr los cubos de ejemplo con las distintas heuristicas, pero algunos se demoran muchisimo. Hay algún máximo  de tiempo de ejecución esperado? Así puedo ver donde ir optimizando mi código 😄 

Saludos!

**Comment by FeBalla** [comment]
Es normal que tarde, ya que se trata de un problema complejo. Sin embargo, para asegurar me gustaría saber a qué te refieres con "muchísimo" (5, 10, 20 segundos?)

**Comment by ceosorio** [comment]
> Es normal que tarde, ya que se trata de un problema complejo. Sin embargo, para asegurar me gustaría saber a qué te refieres con "muchísimo" (5, 10, 20 segundos?)

Facil 10 minutos en algunos casos. Otros no los he visto xq había pasado demasiado tiempo.

**Comment by FeBalla** [comment]
Y eso usando los problemas de ejemplo?

Nosotros hicimos una implementación muy sencilla, que todos/as/es deberían poder hacer fácilmente a partir de lo visto varias veces en ayudantías/clases y nunca tomaba más de 20 segundos.

Podríamos relajar los criterios hasta 40 segundos quizás (**aclaren todo esto del tiempo de ejecución en el README**), pero 10 minutos se nos volvería inviable de revisar dada la cantidad de tareas 😢

**Comment by ceosorio** [comment]
Perfecto,

Si también me parece raro que se demore tanto. Usando `line_profiler` me sale que en lo que mas se demora es en el `.succesors()` :(

Voy a ver que puede ser. Gracias por la respuesta :smile:
