### ISSUE TITLE
DCCubo Rubik - problema al importar rubik.cube

### ISSUE THREAD

**Issue by llambias** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#51]
hola, el programa se se cae al hacer `from rubik.cube import Cube`, tal como estaba en el archivo cube.py subido para hacer la tarea, sin ninguna modificación, a pesar de haber hecho el `pip install rubik-cube` como lo decía el README

**Comment by FeBalla** [comment]
Hola, para poder ayudarte **necesitaríamos más información respecto al error**. Sin embargo, por la experiencia que he tenido a lo largo del curso, creo que podría tratarse de un **problema del intérprete** que estás usando. Esto sucede cuando tienes más de una versión de Python y, por ejemplo, se te instala la librería en la 3.5, pero estás usando la 3.10.

También he visto este tipo de problemas cuando usan VSCode y el intérprete no es el correcto. Si te fijas, abajo debería decir algo como _Python Interpreter_. Puedes clickear ahí y verifica que el ejecutable de Python que se esté usando sea algo del estilo `Local/AppData/blablabla/python.exe` y que no sea algún archivo random que esté por ahí en tu PC.

Si algo de eso funciona, agradecería que respondieras qué fue; y si no funciona nada, poner una screenshot del error.

**Comment by llambias** [comment]
![image](https://user-images.githubusercontent.com/80849968/168405218-be267dfc-5599-481e-83ff-1ba4d0ec2f96.png)

**Comment by FeBalla** [comment]
¿Probaste revisando si el intérprete que usas está correcto?

![issue](https://user-images.githubusercontent.com/48292394/168407786-428f56dc-e688-493c-858f-60906acbd865.png)

Deberías clickear primero en donde apunta la flecha (1) y luego se te desplegará un menú como el que apunta la flecha (2), ahí debes clickear un ejecutable que sea como el de la imagen y ver si es que tienes más de alguna versión.

**Comment by FeBalla** [comment]
Dado que no hay nueva actividad, cerraré la _issue_ por ahora

**Comment by llambias** [comment]
![image](https://user-images.githubusercontent.com/80849968/168924120-7c0b895f-8c2e-4467-a2e4-7c72fa349c56.png)

hola, perdón por demorarme en contestar, pero sigo con el problema y  solo tengo una versión de python instalada, y esto incluso le me lo confirmo el ayudante el día lunes en el bloque de la ayudantía.

**Comment by j4vito** [comment]
Tenía el mismo problema, me sirvió esto:

pip uninstall rubik-cube
pip uninstall rubik
pip install rubik-cube
