### ISSUE TITLE
DCCubo - Actividad 3 y 4

### ISSUE THREAD

**Issue by BrunoFarfan** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#52]
Hola!

De qué forma se espera que hagamos el desarrollo matemático? Se espera que hagamos un desarrollo a mano y lo transformemos en un pdf?
Y en la actividad 4, se espera que escribamos un pdf igualmente?

**Comment by FeBalla** [comment]
Lo ideal es que utilizaran algo como LaTex, que permite escribir cosas matemáticas de forma sencilla y exportar a PDF (pueden usar Overleaf que provee un editor online para LaTex).

Podrían escribir eventualmente a mano y luego pasarlo a un PDF, no hay problema con eso, pero deben asegurarse que todo sea muy legible y fácil de entender, por lo que **recomendaría** asegurarse con algo digital desde el inicio.

**Comment by fran-gl** [comment]
> Lo ideal es que utilizaran algo como LaTex, que permite escribir cosas matemáticas de forma sencilla y exportar a PDF (pueden usar Overleaf que provee un editor online para LaTex).
> 
> Podrían escribir eventualmente a mano y luego pasarlo a un PDF, no hay problema con eso, pero deben asegurarse que todo sea muy legible y fácil de entender, por lo que **recomendaría** asegurarse con algo digital desde el inicio.

Hola! ¿Se puede escribir en word y pasar a pdf?
