### ISSUE TITLE
DCConecta-4 - Error con bombas

### ISSUE THREAD

**Issue by ShescBlank** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#53]
Hola :D

Siguiendo lo recién conversado en la issue #49, implementé el comportamiento aleatorio en los primeros pasos y mi código comenzó a caerse en algunas de las 100 simulaciones, en específico cuando se quiere utilizar una bomba. Me puse a investigar si había roto algo con mis cambios así que decidí correr 100 simulaciones del código original (solo manteniendo mi implementación de la poda alpha-beta para que el código no se tarde demasiado) pero el código se sigue cayendo en la rara ocurrencia de querer utilizar una bomba.

El error es el siguiente:
![image](https://user-images.githubusercontent.com/53873288/168428962-2f5f84a1-8fa9-461e-99df-d35f2e950d1d.png)

A ustedes les funciona bien el uso de bombas? Muchas gracias de antemano

**Comment by CataAlamos** [comment]
Hola!! Me puedes mandar un email con tu código para revisar? El email es catalina.alamos@uc.cl

**Comment by CataAlamos** [comment]
Hay un error en el código base de minimax, vamos a subir el archivo correcto pronto.

**Comment by FeBalla** [comment]
Hola!
Hemos hecho un nuevo _commit_ en el repositorio _template_, para que lo puedan **actualizar en sus repositorios personales**. El [_commit_ con el cambio es este.](https://github.com/IIC2613-Inteligencia-Artificial-2022-1/Tarea-2/commit/601fbbf21a19399fac7c955b4641784871247715)
