### ISSUE TITLE
DCConecta4 - Manejar empates

### ISSUE THREAD

**Issue by ghost** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#54]
Hola, podemos modificar el archivo main.py para que pueda retornar algo en caso de que haya un empate entre los dos jugadores? O nunca debe haber un empate?

**Comment by CataAlamos** [comment]
Hola! Es muy poco probable porque están haciendo uso de distintas funciones de evaluación. Sin embargo, si tu sientes que sería un aporte a tu código, siente libre de poner el caso de empates.

**Comment by ghost** [comment]
Gracias!

**Comment by tcouso** [comment]
Hola! Comento en este issue porque cuando corro las 100 simulaciones estoy llegando a un caso de empate de vez en cuando, lo que provoca que el código se caiga. 

Al imprimir el tablero, se vé que el juego es correcto, así que escribo para preguntar si creen que sea un escenario válido , o si debería asumir que este comportamiento refleja un error que estoy cometiendo en alguna parte. Quedo atento a cualquier comentario.

Saludos!

**Comment by CataAlamos** [comment]
Hola! Has hecho pull de la nueva repo? Arreglamos el bug de los empates

**Comment by tcouso** [comment]
Arreglé un par de cosas, pero no cachaba donde estaba el bug de los empates. Está en alguno de los dos issues con tag "importante"?

**Comment by CataAlamos** [comment]
Esta en la repo de la tarea 2! Espero que eso solucione tu problema

**Comment by tcouso** [comment]
Lo acabo de ver, mala mía. Muchas gracias por la ayuda!
