### ISSUE TITLE
DCCubo Rubik: consulta sobre tiempo de ejecucion

### ISSUE THREAD

**Issue by Pabloski100** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#56]
Hola, estoy teniendo problemas similares a los mencionados en la issue #50 y queria consultar algo que tal vez podria ayudar (al menos a mi implementacion). Mi funcion search esta inspirada en la vista en clases, donde se usa un diccionario de generados en vez de una lista closed (que se da en la clase Astar)

Queria saber si podrian orientarme respecto a ese detalle de la implementacion ¿Es algo importante usar la lista closed o es equivalente a usar un diccionario de generados?

**Comment by SugarFreeManatee** [comment]
Hola! Está perfecto utilizar un diccionario de generados.
