### ISSUE TITLE
DCCubo Rubik: sobre uso de weighted astar para bajar los tiempos de ejecución

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#58]
Hola buenas, quería preguntar si tenemos permitido usar weighted astar en esta parte para disminuir los tiempos de resolución de los problemas. Desde ya gracias.

**Comment by SugarFreeManatee** [comment]
Hola! No está permitido, pues se debe mantener la optimalidad de la solución.
