### ISSUE TITLE
State del cubo

### ISSUE THREAD

**Issue by nicolaszanni** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#59]
Hola. En la parte del cubo, se le entrega por defecto la solución al cubo para que ese sea su state, sin embargo, la clase cubo no tiene atributo state para ir cambiandolo y poder generarar los sucesores, ya que los sucesores se generan a través de la información del state que inicialmente es la solución.

**Comment by SugarFreeManatee** [comment]
Hola! No se si entendí bien tu pregunta. El módulo cube tiene un método sucesores que genera todos los estados posibles a un movimiento del estado actual.

**Comment by nicolaszanni** [comment]
Sí, eso lo tengo claro.
El tema es que en A* cuando iteramos el open y seleccionamos el nodo a expandir, necesitamos sus sucesores.
Pero los nodos no tienen sucesores, sí la clase cubo, por lo que se le debería pasar a la clase cubo un state con la información del nodo pero eso es lo  que me complica hasta ahora.

**Comment by SugarFreeManatee** [comment]
Ah ya entiendo. Recuerda que puedes inicializar un cubo usando un flat string como estado, te sugiero que utilices eso al momento de generar los sucesores de un nodo.

**Comment by nicolaszanni** [comment]
Buena, te pasaste!
