### ISSUE TITLE
[T1] DCClue: "haber estado en la escena de crimen antes del tiempo de descubrimiento"

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#6]
Hola, solo para confirmar, los sospechosos y culpables cuando dice que tienen que haber estado en la escena de crimen antes del tiempo de descubrimiento, incluye el tiempo de descubrimiento? Sé que tomando literal lo que sale en el enunciado se respondería mi duda, pero quería corroborar porque por lo menos a mí me haría un poco de sentido que se incluyera.

Gracias

**Comment by vWing7** [comment]
Hola, es como dice el enunciado, es antes, es decir no se incluye el tiempo de descubrimiento. Si quieres modelarlo mentalmente, podrías pensar que el culpable no puede cometer el crimen al mismo tiempo que se descubre.

**Comment by JuanpaBC** [comment]
oka bkn gracias!
