### ISSUE TITLE
DCCubo Rubik: consulta sobre rendimiento de heuristica de ejemplo

### ISSUE THREAD

**Issue by Pabloski100** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#60]
Hola, he estado trabajando en el rendimiento de mi implementación de A*

Mi situación actual es la siguiente:
- En mi implementación ocupo el Binary Heap y tengo un diccionario de generados (como en el ejemplo del profesor)
- Se que mi implementación funciona, porque he logrado resolver cubos de baja complejidad dados por el método shuffle_cube
- Aun así, si aumento la complejidad más allá de 5, el tiempo de resolución comienza a ser demasiado, a veces simplemente no logrando terminar.
- He hecho cambios pequeños en mi código (como probar weighted A* ) pero no logro mejorar nada

Creo que se me acabaron las alternativas de cosas que cambiar en mi código, por eso, quería preguntar ¿Que tan buena es la heurística de ejemplo? Mi idea era implementar las heurísticas pedidas una vez que mi A* funcionara bien con la de ejemplo, pero si la heurística de ejemplo es poco eficiente tal vez lo que hice no esta mal y solo necesita otra heurística.

**Comment by SugarFreeManatee** [comment]
Hola! La heurística de ejemplo es terrible :P solo está para mostrar el formato.
