### ISSUE TITLE
DCCubo Rubik: consulta sobre eficiencia de heurírsticas en cubos de ejemplo

### ISSUE THREAD

**Issue by Pabloski100** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#61]
Hola (y perdón el spam en domingo) pero quería consultar sobre los cubos de ejemplo dados, ya que 2 heurísticas de las que piden implementar se demoran demasiado intentando resolver todo el set (al menos en mi implementación)

No se si puedo compartir cuales, pero una me resuelve un par de casos y luego queda trabajando demasiado tiempo, la otra, se queda trabajando en el primer caso, ¿Es obligatorio usar ese set de ejemplos o podría crear los míos con algunos casos más simples? Es que ya no se donde optimizar para mejorar rendimiento

**Comment by SugarFreeManatee** [comment]
Hola! Mira el primer cubo es el mas difícil, puedes crear los tuyos simplificados para probar las heurísticas pero se evaluarán con los que vienen dados o cubos de dificultad similar, y el estudio de tiempo y nodos expandidos debe ser con cubos de complejidad más alta para notar bien la diferencia en rendimiento.

**Comment by mc-cari** [comment]
Hola, me encuentro con el mismo problema, hay un tiempo límite en que debiera terminar la ejecución de todos los ejemplos?

**Comment by FeBalla** [comment]
> Hola, me encuentro con el mismo problema, hay un tiempo límite en que debiera terminar la ejecución de todos los ejemplos?

Cuánto te está tardando por caso individual?

**Comment by mc-cari** [comment]
> > Hola, me encuentro con el mismo problema, hay un tiempo límite en que debiera terminar la ejecución de todos los ejemplos?
> 
> Cuánto te está tardando por caso individual?

Normalmente menos de un minuto, pero en el cubo de ejemplo 4 no he logrado que termine (> 20 min) y ha expandido mas de 1.000.000 estados

**Comment by SugarFreeManatee** [comment]
Dependiendo de la heurística es posible que no encuentre solución en los cubos normales (dentro de un tiempo razonable), en cuyo caso puedes anotar esto en tu análisis. Prueba con los cubos fáciles que subimos para ver que no sea algo de la implementación, para esos ninguna heurística debiese demorar más de 20 segundos (tiempos pueden variar según tu procesador pero no van a ser 20 minutos :P)

**Comment by mc-cari** [comment]
Entiendo gracias

**Comment by ceosorio** [comment]
> Dependiendo de la heurística es posible que no encuentre solución en los cubos normales (dentro de un tiempo razonable), en cuyo caso puedes anotar esto en tu análisis. Prueba con los cubos fáciles que subimos para ver que no sea algo de la implementación, para esos ninguna heurística debiese demorar más de 20 segundos (tiempos pueden variar según tu procesador pero no van a ser 20 minutos :P)

Hola!, estoy teniendo problemas también con el Cubo 4 de los ejemplos. Los fáciles no tienen problemas y el resto de los de ejemplo tampoco, pero ese cubo en particular nunca termina (con ninguna heurística). Si es así, puedo agregar ese detalle al readme?

**Comment by FeBalla** [comment]
> > Dependiendo de la heurística es posible que no encuentre solución en los cubos normales (dentro de un tiempo razonable), en cuyo caso puedes anotar esto en tu análisis. Prueba con los cubos fáciles que subimos para ver que no sea algo de la implementación, para esos ninguna heurística debiese demorar más de 20 segundos (tiempos pueden variar según tu procesador pero no van a ser 20 minutos :P)
> 
> Hola!, estoy teniendo problemas también con el Cubo 4 de los ejemplos. Los fáciles no tienen problemas y el resto de los de ejemplo tampoco, pero ese cubo en particular nunca termina (con ninguna heurística). Si es así, puedo agregar ese detalle al readme?

Sí, totalmente, todos esos detalles deberían ser incluidos en un buen README. Los demás cubos te funcionan?

**Comment by ceosorio** [comment]
> > > Dependiendo de la heurística es posible que no encuentre solución en los cubos normales (dentro de un tiempo razonable), en cuyo caso puedes anotar esto en tu análisis. Prueba con los cubos fáciles que subimos para ver que no sea algo de la implementación, para esos ninguna heurística debiese demorar más de 20 segundos (tiempos pueden variar según tu procesador pero no van a ser 20 minutos :P)
> > 
> > 
> > Hola!, estoy teniendo problemas también con el Cubo 4 de los ejemplos. Los fáciles no tienen problemas y el resto de los de ejemplo tampoco, pero ese cubo en particular nunca termina (con ninguna heurística). Si es así, puedo agregar ese detalle al readme?
> 
> Sí, totalmente, todos esos detalles deberían ser incluidos en un buen README. Los demás cubos te funcionan?

con una de las heuristicas sip. Solo ese cubo se queda pegado.
