### ISSUE TITLE
DCCuboRubik - Duda parsed.txt

### ISSUE THREAD

**Issue by ShescBlank** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#63]
Holaa

En relación a la issue #47, entendí que hay que retornar el trace del último nodo de la solución encontrada para que se genere bien el parsed.txt y poder usar el simulador. El resultado en consola es bello con los colores, los pasos y los distintos estados del cubo hasta llegar a la solución, pero mi problema es que el parsed también queda escrito con los estados del cubo y no solo con los pasos a seguir (como el video del simulador), es decir, en vez de quedar U' B R', queda U' (estado cubo) B (estado cubo) R' (estado cubo).

Hay algo que me está faltando para que quede como el video o debería bastar con retornar sol como el trace del último nodo de mi solución?

Muchas gracias :D

**Comment by SugarFreeManatee** [comment]
1. Que weno que te gustaron los colores :D
2. Eso me suena a que subimos una version anterior del parser, posiblemente encontraste un bug D: 
Te aviso cuando lo sepamos

**Comment by mpmunoz13** [comment]
@SugarFreeManatee Tengo el mismo problema! Porfa avisen cuando lo resuelvan :)

**Comment by FeBalla** [comment]
Hola!
En el [último _commit_](https://github.com/IIC2613-Inteligencia-Artificial-2022-1/Tarea-2/commit/bf78428d9a5f6942ebd314d37c45f650fc3178d1) actualizamos el parser. Básicamente, el código más importante que cambia es este:
```py
def parse_algorithm(algorithm):
	algorithm = algorithm.replace('->', ' ').replace('i', '\'')
	algorithm_parsed = []

	for al in algorithm.split('\n'):
		if '->' in al:
			algorithm_parsed.append(al.strip())

	algorithm_parsed = ''.join(algorithm_parsed)
	algorithm_parsed = algorithm_parsed.replace('->', ' ').replace('i', '\'')

	return algorithm_parsed +'\n'
```
