### ISSUE TITLE
DCConecta-4  Actividad 2: Funciones de evaluación

### ISSUE THREAD

**Issue by mpmunoz13** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#64]
Hola, 
Al usar la función de la manera que está implementada me aparece que el token (variable jugador) es siempre X. 
-   two_next_to(board, jugador)
-   three_next_to(board, jugador)
¿Donde debemos pasarle el token?

**Comment by CataAlamos** [comment]
Hola! No debes pasarle el token porque en minimax se le pasa. 

No obstante, notamos que había un error como bien tu dices de que la variable jugador siempre es X. Por lo tanto, estamos intentando arreglarlo ahora.

**Comment by FeBalla** [comment]
> Hola, Al usar la función de la manera que está implementada me aparece que el token (variable jugador) es siempre X.
> 
> * two_next_to(board, jugador)
> * three_next_to(board, jugador)
>   ¿Donde debemos pasarle el token?

En [este _commit_](https://github.com/IIC2613-Inteligencia-Artificial-2022-1/Tarea-2/commit/1e9479a4d6f3c6d536762b173316f21af8c8563b) pueden encontrar cambios que deberían arreglar este bug de los tokens. De todos modos, **este tipo de bugs menores pueden arreglarlos ustedes** y no hay ningún problema, pues son un par de líneas y así no tienen que esperar a que respondamos. Estas cosas las pueden aclarar en el README 😄 Muchas gracias por la corrección
