### ISSUE TITLE
[Astar] Posicion objetivo en heurísticas

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#65]
Hola!

Tengo una pequeña duda, cuando en las heurísitcas se nos pide considerar la distancia entre la posicion de una esquina del estado actual y su posicion objetivo respectiva, tenemos que considerar también la "distancia" de los colores ya que la ficha podría estar con otro orden de colores? O no es necesario y sólo es con la posición en 3D?

Gracias de antemano!

**Comment by SugarFreeManatee** [comment]
Hola! Solo es necesario considerar la posición, no el orden de los colores.

**Comment by Jamesmoreno21** [comment]
okey, muchas gracias!!
