### ISSUE TITLE
DCCubo Rubik - Duda cálculo heurísticas

### ISSUE THREAD

**Issue by ShescBlank** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#66]
Holaa :D

Aprovecho de agradecer por las otras respuestas y creo que esta será mi última issue perdón 😅

También relacionado a la issue anterior #65, me gustaría saber si nos podrían dar un ejemplo del cálculo de las distancias Manhattan en 3D. Si, por ejemplo, tengo una esquina en la posición (1,1,1) y en el cubo solución esa misma esquina debe ir en la posición (-1,-1,-1), entonces la distancia Manhattan dividida en dos es igual a 3? (ya que se requieren hacer 3 movimientos para situar la esquina en su posición). O también debo considerar los movimientos necesarios para que además esté bien orientada con respecto a los colores?

Muchas gracias! 🐧

**Comment by SugarFreeManatee** [comment]
Hola! No es necesario considerar la orientación, en ese caso sería 3.
