### ISSUE TITLE
DCCubo Rubik: print_fun

### ISSUE THREAD

**Issue by mpmunoz13** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#67]
Hola, 
Print_fun solo me está imprimiendo la solución ya que la variable color es siempre True. Le estoy pasando el string completo con el tiempo de ejecucion y nodos expandidos pero solo me retorna la solución. ¿Se puede editar el argumento entregado a print fun para imprimir el resto de la información con el print normal?

**Comment by SugarFreeManatee** [comment]
Hola! No se si entiendo el problema, pero puedes editar la función.
