### ISSUE TITLE
DCCubo Rubik: Posición final

### ISSUE THREAD

**Issue by PDominguezW** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#68]
Hola!
En el bonus, cuando hablan de pasos de la esquina para llegar a la posición correcta, ¿Se refieren a la posicion correcta en terminos de coordenadas, o tambien tiene que ser la posición correcta en la rotación de la esquina?

**Comment by Jamesmoreno21** [comment]
Hola! Yo pregunte si teníamos que considerar la posición solamente o la posición y el orden de los colores  (que es lo mismo que dices de la rotación) y me dijeron que era solo por posición.

**Comment by FeBalla** [comment]
Hola! como dice el compañero, es solo respecto a la posición
