### ISSUE TITLE
[T2] [DCConecta-4] Primera jugada random

### ISSUE THREAD

**Issue by fran-gl** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#69]

**Comment by fran-gl** [comment]
Hola! En la Actividad 3 de DCConecta-4 hice que la primera jugada sea random, pero se me siguen generando juegos iguales en muchas de las 100 partidas. ¿Es posible hacer que la primera jugada **de cada jugador** sea random, y/o asumir que la primera jugada no va a ser colocar una bomba? De esta forma se me generan más juegos distintos, por eso pregunto.

Muchas gracias de antemano.

**Comment by CataAlamos** [comment]
Hola, te sugiero que veas la issue #49 ahi se explica que tu puedes darle un comportamiento aleatorio a tu programa. No te olvides especificarlo en el Readme!

**Comment by fran-gl** [comment]
Ok, gracias.
