### ISSUE TITLE
Duda sospechoso - DCClue

### ISSUE THREAD

**Issue by ignacioarteaga99** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#7]
Hola, en el enunciado de la tarea se señala que el culpable debe, aparte de mentir, haber estado en el lugar del crimen antes del tiempo de descubrimiento de este. Sin embargo, en los ejemplos "prob1.lp" y "prob2.lp", el culpable (Nico) no "pasa" o no se declara que pase por el lugar del crimen, por lo cual me quedan dudas de si el enunciado está mal o es el ejemplo.

**Comment by FeBalla** [comment]
Recuerda que el objetivo del programa es que tú generes una **versión válida** de cómo ocurrieron los hechos. Por lo tanto, si tienes suficiente información para detectar al culpable, pero no para saber cuándo estuvo en el lugar del crimen, entonces debes entregar un modelo en el que haya estado en algún tiempo antes de TD (tiempo descubrimiento) en el lugar, **pudiendo haber muchas opciones válidas**. ¿Se entiende?
