### ISSUE TITLE
[DCConecta-4] Duda ambas IAs con maximizing_player

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#70]
Hola! 

Espero estén bien, tengo una duda puntual respecto a la simulación de la 100 partidas. Por cómo está modelado, si ponemos a jugar 2 IAs entre sí ambas serían maximazing_player, por lo que está en el template [template](https://github.com/IIC2613-Inteligencia-Artificial-2022-1/Tarea-2/blob/main/02%20-%20DCConecta-4/player.py) en la línea 124. En mi caso tengo la duda si esto está bien, pues se supone que uno debería partir como minimizing y otro como maximizing, pero si me estoy equivocando agradecería su aclaración.

Gracias de antemano!

**Comment by CataAlamos** [comment]
Hola!! La idea de maximazing player y minimizing player son como tu evalúas tus pasos. Como tengo dos IAs, IA 1 y IA 2,  como IA 1 trata de conseguir el puntaje más grande posible entonces es el maximazing y asume que IA 2 va a jugar en la manera que más le perjudica, por eso se ve como un minimzing player. Lo mismo hace la IA 2, pero esta intenta mejorar su puntaje y ve a su contrincante como un minimizing player.

**Comment by Jamesmoreno21** [comment]
Ahh yaya, me quedó clarísimo. Muchas gracias!!

**Comment by CataAlamos** [comment]
De nada, mucha suerte en la tarea!
