### ISSUE TITLE
Consulta estado inicial DCCRubik

### ISSUE THREAD

**Issue by AlonsoZamorano** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#71]
Buenos días,
Quisiera consultar sobre ¿por qué el estado inicial del DCCRubik parte con la solución?. Pensaba en que tenía que iniciar desde el estado revuelto para iniciar la resolución.
Muchas gracias.

**Comment by SugarFreeManatee** [comment]
Hola! Los estados iniciales efectivamente son los cubos no resueltos que se encuentran en los archivos de texto.

**Comment by AlonsoZamorano** [comment]
Aaaahh perfecto!
Muchas gracias
