### ISSUE TITLE
DCCubo Rubik Ubicación piezas centrales

### ISSUE THREAD

**Issue by nlewin99** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#72]
Hola cómo puedo ver el estado inicial de las piezas centrales que se supone que son fijas?

**Comment by SugarFreeManatee** [comment]
Hola! No se si entiendo bién la pregunta, pero cada pieza central se encuentra en el 0 de algún eje, por ejemplo para acceder a la pieza central de arriba debes indexar el cubo en (0, 0, 1)

**Comment by nlewin99** [comment]
Mi pregunta es sobre como saber el color de cada pieza central para poder buscar el estado final de la solución donde cada cara este completa con el color correspondiente.

**Comment by SugarFreeManatee** [comment]
Cada pieza tiene un atributo colors que muestra los colores de esa pieza, en el caso de las piezas centrales es un caracter único con la primera letra.
