### ISSUE TITLE
DCCubo Rubik Solucion Cubo

### ISSUE THREAD

**Issue by nlewin99** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#73]
Hola estoy un poco perdido con el goal final del cubo. No entiendo si cada pieza tiene su goal o un conjunto de posibles goals o más bien el cubo como tal tiene un goal. 
Ademas tengo dudas con el estado 'sol' que viene al inicio de cube.py, corresponde a la solución final?
Saludos muchas gracias.

**Comment by SugarFreeManatee** [comment]
Hola! Sí, sol es la solución final del cubo. 
Con respecto a tu primera pregunta, el cubo está compuesto por piezas por lo que hablar de su configuración es equivalente a hablar de la posición de cada una de sus piezas. Dependiendo de si deseas verificar si está solucionado o calcular las heurísticas que se piden te conviene usar el string del cubo o la posición de sus piezas individualmente.

**Comment by nlewin99** [comment]
Ok gracias, una ultima duda respecto a la solucion final, 'sol' es la unica solución final a la cual debemos apuntar o de ahí debemos encontrar otras equivalentes?

**Comment by SugarFreeManatee** [comment]
Debido a las limitaciones de los movimientos del cubo, sol es la única solución posible.
