### ISSUE TITLE
[T2] [DCCubo] Heurísticas a incluir en comparación de actividad 4

### ISSUE THREAD

**Issue by fguinez** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#74]
Hola!

En el estudio empírico de la actividad 4 de DCCubo Rubik, ¿debemos considerar las 3 heurísticas o solo las que demostramos que eran admisibles en la actividad 3?

**Comment by SugarFreeManatee** [comment]
Hola! Mientras esté documentado y justificado queda a tu criterio.
