### ISSUE TITLE
DCubo Rubik - problema al importar rubik.cube 

### ISSUE THREAD

**Issue by llambias** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#75]
hola, ya había creado un issue pero no pude resolver el problema, al importar la librería `rubik.cube` me aparece como si no la hubiera instalado, e incluso le pregunte al ayudante el día lunes.
![image](https://user-images.githubusercontent.com/80849968/169446544-1d009b61-2cbd-46a4-a7c6-4778459c5e64.png)
antes me dijeron que podía ocurrir si tenia múltiples versiones de python, pero solo tengo una, esto evita que pueda testear la parte 1 de la tarea.

**Comment by SugarFreeManatee** [comment]
Cerrando por duplicado de la issue #51
