### ISSUE TITLE
 DCConecta-4 - Archivos Bonus

### ISSUE THREAD

**Issue by fguinez** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#77]
Hola!

En caso de que realicemos el bonus de DCConecta-4, ¿se debe realizar un pdf adicional a `estudio.pdf`?

Para el caso del código, ¿podemos reutilizar `simulate.py` dejando una línea comentada que intercambie entre actividad3 y bonus?

**Comment by CataAlamos** [comment]
Hola!! Si, debes crear un pdf adicional. Respecto a tu segunda pregunta, mientras que explique en el Readme como lo hiciste y que cambios debe hacer el ayudante corrector para que pueda ejecutar tu código no hay problema.

**Comment by fguinez** [comment]
Gracias!
