### ISSUE TITLE
DCConecta-4 Duda funciones de evaluación y profundidad Minimax

### ISSUE THREAD

**Issue by Skablop** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#78]
Hola,

En el código aparecen las siguientes líneas para calcular el score del tablero luego de alcanzar la profundidad deseada 

```     
 if maximizing_player:		
        return (None, [False, None], score_function(match.board, token))
 else:
        return (None, [False, None], -score_function(match.board, opponent_token)) 
```

Si el depth es par (4 por ejemplo), entonces la función minimax iteraria los jugadores max => min => max => min => max
y usaría este último para calcular el score de los tableros, es decir, usando la línea:
```  return (None, [False, None], score_function(match.board, token)) ```   

En cambio si es impar, usaría ```  return (None, [False, None], -score_function(match.board, opponent_token)) ```  

Esto implica que si el depth es impar, entonces nuestro player IA (el max), trataría de maximizar el -score del oponente. Con la heurística de three_next_to por ejemplo, intentaría hacer que el oponente tenga la menor cantidad de tríos, sin importarle realmente los propios.

No se si este es el comportamiento correcto, ya que asumo que lo que se quiere es hacer la mayor cantidad de tríos, pero el comportamiento del programa cambia mucho según si el depth que se le asigna a los players es par o impar (si es par maximiza los tríos propios, que es lo buscado).

Eso, ¿hay algo que esté entendiendo mal?

Perdón por la consulta tan larga.

**Comment by ignaciovilla** [comment]
Hola! No te preocupes por el largo de la consulta, para eso estamos.

Con respecto a la pregunta, si el depth es impar, minmax entra en:

`else:                                   # "minimizing_player" `
`       return (None, [False, None], -score_function(match.board, opponent_token))`


Por lo que efectivamente "maximiza el -score_function" del oponente, que si te fijas, no es más que minimizarla.
En cuanto al funcionamiento, es correcto que minmax evalué el tablero según su propia función de evaluación, ya sea para el mismo, como para su adversario. Tal vez te hace más sentido si lo piensas como que la función de evaluación es la forma con la que minmax mira al problema, por lo que en base a eso (y usando three_next_to por ejemplo), el va a querer tener la mayor cantidad de tríos, y al mismo tiempo va a querer que su oponente tenga la menor cantidad posible, por lo que va a evaluar la jugada (propia si el depth es par, del oponente si es impar) en base a esa función. 

Avísame si eso responde tu duda!

**Comment by Skablop** [comment]
Hola,

Me queda más claro, pero tengo una última consulta:
Como el depth es fijo (al momento de querer evaluar un tablero "real"), cada vez que quiero evaluar, simulo hasta la profundidad y evalúo el score. 

¿Entonces pasará que, si el depth es 5 por ejemplo, siempre estoy jugando a minimizar los tríos de mi oponente, pero no a maximizar los míos? Porque las evaluaciones de los tableros se calcularían todas con la función ```-score_function(match.board, opponent_token)``` y nunca entran en juego mis fichas (ya que para evaluar uso solo las de mi oponente). Ya que el score del tablero se calcula solo al final del árbol (y asumiendo que el depth "inicial" sea 5, siempre uso la función negativa de las fichas oponentes, pero nunca la que cuenta mis fichas y luego el minimax solo usa esos scores negativos para hacer backtracking hacia arriba del árbol).

No se si se entiende bien la duda, quizá queda un poco más clara enunciada así: Como los scores solo se asignan cuando depth se vuelve 0 (luego solo se va haciendo backtracking y viendo cuál es mayor o menor), si el depth es impar, se usa la fórmula   ```-score_function(match.board, opponent_token)```. ¿Eso no implica entonces que lo único que hago es minimizar los tríos de mi oponente, y en ningún momento realmente considero los míos?

**Comment by ignaciovilla** [comment]
Respondiendo a esta pregunta "¿Eso no implica entonces que lo único que hago es minimizar los tríos de mi oponente, y en ningún momento realmente considero los míos?", no realmente, porque recuerda que si estas usando un depth 5, estas mirando "5 jugadas al futuro", que considera tanto las tuyas como las del oponente. Por lo tanto, minmax va a decidir su jugada en base a lo que vea 5 pasos al futuro, pero considerando la jugada que en cada etapa le retorna más (si es par) o menos (si es impar) valor según la función de evaluación. 

Avísame si eso responde tu duda!

**Comment by Skablop** [comment]
¿Pero esos 5 pasos al futuro siempre los evalúo con el score negativo o no (ya que el score solo se calcula una vez para los nodos hoja y el resto es backtracking)?

 Y en base a eso voy eligiendo lo mejor/peor mientras subo en el árbol.  Pero ese mejor/peor es en torno a las fichas del enemigo y no a las mías,  ya que para calcular ese score negativo solo uso las fichas del enemigo.

Porque entiendo que cuando subo en el árbol voy eligiendo lo mejor/peor, pero es en torno al score que se les dió a los nodos hoja, que en este caso (con depth 5) solo se calcula en base a los tríos del oponente, pero no tratando de maximizar mis tríos (porque nunca calculo el score de mis fichas, una vez que el depth es 5 siempre calculo el score negativo del oponente y voy llenando el árbol a partir de esos valores. Y evitar que mi oponente haga tríos no implica que yo esté maximizando los míos, porque el score negativo ignora los tríos propios).

Por poner un ejemplo, supongamos depth 1, la función three_next_to para X y la situación siguiente:
<img width="576" alt="ejemplo" src="https://user-images.githubusercontent.com/20783702/169873936-48bdf3d7-3949-41d3-a9eb-1f88511796a7.png">

Como minimax tiene depth impar, entonces los nodos hoja se calculan con el score negativo del oponente. Luego, ambos nodos hoja acá tendrían valor 0 (ya que en ninguno el oponente tiene tríos), pero claramente uno mejora el score propio (ya que el la izq tiene un trío con X). Pero como el score ngeativo no revisa las fichas propias, entonces ignora el nodo que claramente aumenta el score propio, y los evalúa a ambos con 0.

**Comment by ignaciovilla** [comment]
"Y en base a eso voy eligiendo lo mejor/peor mientras subo en el árbol. Pero ese mejor/peor es en torno a las fichas del enemigo y no a las mías, ya que para calcular ese score negativo solo uso las fichas del enemigo." En base a esto, con depth = 5, el nodo hoja efectivamente corresponderá a minimizar la jugada del "enemigo", pero en el nivel que esta sobre ese (es decir, par, ej : 4), se va a elegir entre el máximo de esos, por lo que si estas evaluando tus fichas, pero no para todos los niveles. Te recomiendo revisar el siguiente link, hace un ejemplo que deja muy claro el algoritmo.

https://www.javatpoint.com/mini-max-algorithm-in-ai
Avísame si esto responde tu duda!
