### ISSUE TITLE
Archivos de extensión permitidos distintos a .py

### ISSUE THREAD

**Issue by sofiagiagnoni** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#79]
Hola! se puede incluir un archivo .ipynb para adjuntar el proceso de elaboración de gráficos de las heurísticas?

Saludos!

**Comment by FeBalla** [comment]
Sí, no hay problema mientras todas las celdas estén ejecutadas, todo funcione y esté explicado en el README
