### ISSUE TITLE
Duda posición caja y robot cuando robot toma caja

### ISSUE THREAD

**Issue by josetomasgrez** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#8]
Hola!

Cuando un robot toma una caja, ¿la posición de la caja pasa a ser la misma del robot o sigue siendo una casilla adyacente al robot? Si es el primer caso se contradice con la regla de que no puede haber una caja y un robot en la misma casilla, pero si es el segundo habrían movimientos que no se podrían hacer, como que un robot doble en una esquina, porque el conjunto robot-caja usaría dos casillas.

**Comment by FeBalla** [comment]
Lo importante acá es que distingan que la **posición de las cajas tiene una componente adicional (Z)**, por lo que **no puede haber un robot y una caja que está en el suelo (Z=0) en el mismo lugar**, pero si el robot la está cargando (Z=1) sí se puede, de hecho, es la idea.

**Comment by josetomasgrez** [comment]
Gracias!
