### ISSUE TITLE
Duda con correcto funcionamiento de BinaryHeap

### ISSUE THREAD

**Issue by Agustinuv** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#80]
Hola, estaba estudiando por qué el algoritmo de la parte DCCubo se me demoraba tanto, y vi que el BinaryHeap no me estaba ordenando correctamente la open, sucediendo que (como se ve en la foto), no todos los elementos estaban ordenados desde el con menor key hasta el con mayor. A alguien más le pasó algo así o implementé algo mal?

![image](https://user-images.githubusercontent.com/69604905/169907023-42230542-4e26-4b80-b9e0-524c56be2ada.png)

La imagen corresponde al cubo "ROYROYGROBBWRYGBWWOGYRYGBWWOGYBBWRYGBWWOGYBBWRGGORRYOO" tras expandir su estado inicial (`self.open.size` es `12`)

**Comment by SugarFreeManatee** [comment]
Hola! Es dificil decir si el comportamiento que muestras es el esperado. Pero mientras actualices los valores correspondientes al key, h, g del nodo previo a la inserción y utilices los métodos extract e insert del binary heap, debería funcionar correctamente.
