### ISSUE TITLE
Parte 1 Actividad 4 Comparación de heurísticas tiempo ejecución cubos_ejemplo.txt

### ISSUE THREAD

**Issue by sofiagiagnoni** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#81]
hola! En la actividad 4 parte 1 al momento de implementar los gráficos para las distintas heurísticas, el archivo completo de cubos_ejemplo.txt tarda mucho tiempo en ejecutarse con cualquiera de ellas. Además obtener cinco muestras de cada heurística aumenta considerablemente el tiempo de ejecución esta actividad. ¿Es posible que para la realización de esta parte puedan considerarse  algunos de los cubos presentados en cubos_ejemplo.txt?

Saludos

**Comment by ignaciovilla** [comment]
Hola! Es lo segundo, debes elegir 5 cubos y evaluar cada heurística sobre ellos.
Avísame si eso responde tu duda!

**Comment by sofiagiagnoni** [comment]
sii gracias!
