### ISSUE TITLE
DDCubo - Supuestos actividad 3

### ISSUE THREAD

**Issue by edovt** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#82]
Hola!

Para la pregunta 3.2 del DCCubo, ¿asumimos que, a partir de cualquier estado, siempre existe un camino a algún estado objetivo?

**Comment by SugarFreeManatee** [comment]
Hola! Sí, puedes asumir esto pero debes dejarlo claro en tu respuesta.
