### ISSUE TITLE
[T3] Dudas Actividad 6 Parte 1

### ISSUE THREAD

**Issue by fran-gl** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#83]
Hola! Tengo unas dudas de la actividad 6 de la parte 1 de la tarea 3.

1. En el método `fit`, ¿se debe entrenar el árbol A1 con todos los datos de `X` y luego predecir también con todos los datos de `X`?

2. En el método `fit`, ¿qué sucede si entre los árboles A1 y A2 se predicen todas las instancias de `X` correctamente? ¿Con qué se entrena A3 en ese caso?

Muchas gracias de antemano.

**Comment by FeBalla** [comment]
1. Sí, siempre que hablemos en esa pregunta de las predicciones que falla un árbol son sobre el set de entrenamiento completo. Entonces, A2 se entrena con lo que falla A1 en entrenamiento y A3 se entrena con lo que falla A2 y A1 en entrenamiento completo también.
2. Lo dejamos a su criterio, pues es algo que habría que manejar. Sin embargo, eso sería **demasiado raro** que pasara con la cantidad de datos que tienen. Sea lo que sea que hagan, pueden explicarlo, la idea es que ustedes se aventuren con esos detalles.

**Comment by fran-gl** [comment]
Oka, gracias!

**Comment by juanjouriarte** [comment]
Hola, con respecto al set de entrenamiento completo. Te refieres a X completo o una porción de X destinada a ser Xtrain?

Para ser mas claros debemos hacer fit(X_completo) o fit(X_train)?. Siendo X_train una muestra aleatoria del 20% de X_completo
