### ISSUE TITLE
[T3] Duda Pregunta 1 Actividad 6

### ISSUE THREAD

**Issue by juanjouriarte** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#84]
Hola, con respecto a la pregunta que se contesta en esta issue https://github.com/IIC2613-Inteligencia-Artificial-2022-1/Syllabus/issues/83#issuecomment-1144437682.

Cuando se habla de X_train completo se trata de una porción aleatoria de X o se trata de todo X. 

Para que se entienda mejor. ¿Deberiamos hacer el fit(X_train) o fit(X)?.

**Comment by ignaciovilla** [comment]
Hola! Efectivamente el método Fit recibe X_train (Fit(X_train)). Dentro de él debes hacer la separación indicada en el enunciado.
Avísame si te responde la duda!

**Comment by juanjouriarte** [comment]
> Hola! Efectivamente el método Fit recibe X_train (Fit(X_train)). Dentro de él debes hacer la separación indicada en el enunciado. Avísame si te responde la duda!

Si, a la perfección. Gracias!
