### ISSUE TITLE
[T3] [SVM] Actividad 6

### ISSUE THREAD

**Issue by fran-gl** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#86]
Hola! Me surgió una duda de la actividad 6 de la parte de SVM de la tarea 3. Para los textos que tenemos que escribir, ¿hay que escribir ambos el "new_headline" y el "news_article", o depende de cuál/cuáles columnas decidimos dejar para entrenar el SVM?

Gracias de antemano.

**Comment by FeBalla** [comment]
Todo depende de lo que hayan hecho, porque quedaba a su criterio cómo trabajar el _dataset_. Por ejemplo, si usaron ambas columnas, deberían crear los textos de ambas. Si usaron una, entonces solo una y así con cada caso.

**Comment by fran-gl** [comment]
Perfecto, gracias!
