### ISSUE TITLE
T3 Árboles de Decisión

### ISSUE THREAD

**Issue by BrunoFarfan** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#87]
Para la actividad 6, qué pasa si es que A<sub>1</sub> o A<sub>2</sub> no fallan en clasificar ningún caso?
Por ejemplo, si el A<sub>2</sub> clasifica todos los casos correctamente, entonces A<sub>3</sub> no tiene nada que clasificar. No debemos crear A<sub>3</sub> en ese caso? Y qué pasaría en ese caso con w<sub>3</sub>?

**Comment by FeBalla** [comment]
Hola!
Esto ya fue respondido en #83
