### ISSUE TITLE
[T3] Duda Árboles de Decisión

### ISSUE THREAD

**Issue by fran-gl** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#88]
Hola! Una duda, en la parte de árboles de decisión de la tarea 3, ¿debemos utilizar un set de validación?, ¿o queda a nuestro criterio? Pregunto porque solo se mencionan los set de entrenamiento y de test, pero también se habla de los hiperparámetros.

Muchas gracias de antemano.

**Comment by FeBalla** [comment]
Siempre deberían ver alguna manera de validar los hiperparámetros que no implique usar el set de test. Pueden dejar un set de validación o pueden usar la función `cross_val_score` de sklearn :)

**Comment by fran-gl** [comment]
Oka, muchas gracias!

**Comment by fran-gl** [comment]
> Siempre deberían ver alguna manera de validar los hiperparámetros que no implique usar el set de test. Pueden dejar un set de validación o pueden usar la función `cross_val_score` de sklearn :)

Hola! Una duda, en una ayudantía después de utilizar el set de validación, lo juntan con el set de entrenamiento para entrenar el modelo final con esos datos (entrenamiento + validación). ¿Se puede hacer eso en la tarea?
