### ISSUE TITLE
[T1] Duda generar culpable DDClue

### ISSUE THREAD

**Issue by fran-gl** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#9]
Hola! Tengo una duda de la parte DDClue de la tarea 1.
¿Siempre se podrá deducir quién es el culpable a partir de lo que se entrega en los archivos de problemas ```prob.lp```? Es decir, ¿siempre va a haber una contradicción/mentira en estos archivos? Si es que no, ¿nuestro programa debería encontrar un culpable igualmente con la información que tiene?

Por ejemplo, en caso de que se entregue un archivo así:
<img width="703" alt="Captura de Pantalla 2022-04-10 a la(s) 16 42 29" src="https://user-images.githubusercontent.com/62031688/162639044-e78d4685-bdb7-405e-8286-e75866b10ae7.png">
¿Nuestro programa tiene que generar un escenario donde felipe sea el culpable? ¿O no necesariamente debería encontrar un culpable en este caso?

Muchas gracias de antemano.

**Comment by FeBalla** [comment]
Las instancias con las que nosotros probaremos su tarea **tendrán siempre la información suficiente para que haya un único culpable**. Sin embargo, no veo ninguna razón para que su programa se caiga si no hay información suficente (eventualmente podría no terminar de computar si es que existen muchos modelos).

Si quieren manejar esa situación, queda totalmente a criterio de ustedes 😃

**Comment by fran-gl** [comment]
Oka, gracias!
