### ISSUE TITLE
Tarea 3 Arboles de decisión actividad 4

### ISSUE THREAD

**Issue by Mario-uc** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#90]
Hola buenas, no me quedó muy claro a que se referían con esta pregunta. Si me la podrían explicar 

¿Cuántas instancias para cada categoría de Survived hay en cada set? ¿Están aceptablemente
balanceadas? ¿Qué riesgos existen si es que están demasiado desbalanceadas?

**Comment by FeBalla** [comment]
Hola!
Tal como hemos visto en clases y ayudantías, es importante que los datos que usemos para entrenar y evaluar a un modelo sean suficientemente representativos. Por ejemplo:

Si tenemos un _dataset_ con 100 datos, donde 50 son de la categoría 0 y los otros 50 de la categoría 1. Luego, ocupamos 70 datos para entrenar un SVM, pero de esos 70, 50 corresponden a la categoría 0. Lo más probable es que nuestro modelo quede mal entrenado porque se entrenó con datos donde la población de la categoría 0 se ve sobre-representada y, en consecuencia, esté mal generalizado.

Dicho esto, la pregunta apunta a que verifiquen si están representando bien la población en sus sets de entrenamiento y test.
