### ISSUE TITLE
[T3] Pregunta 1 Actividad 6 metodo fit

### ISSUE THREAD

**Issue by mc-cari** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#91]
Hola, el metodo fit recibe solo X, o recibe los datos X y las etiquetas "y" de esos datos por separado?

**Comment by aamedinaj** [comment]
Para esta clase de preguntas resulta muy útil ver la [documentación](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html#sklearn.tree.DecisionTreeClassifier.fit). Pero recibe X e y por separado.

**Comment by mc-cari** [comment]
Vale gracias, si mi duda era en el metodo fit en la clase custom

**Comment by FeBalla** [comment]
El método `fit` custom es una imitación de los modelos de sklearn, así que también necesitas los datos y sus etiquetas!
