### ISSUE TITLE
[T3] Hiperparámetros

### ISSUE THREAD

**Issue by fran-gl** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#92]
Hola! Tengo una duda con respecto a ajustar los hiperparámetros de los modelos. ¿Hay una cantidad mínima de hiperparámetros que tenemos que ajustar según el modelo, o se deben ajustar todos?

Muchas gracias de antemano.

**Comment by IgnacioMedel** [comment]
Agregando a la pregunta de mi compañera, de ajustar los hiperparametros, ¿estos pueden tener valores None?

**Comment by aamedinaj** [comment]
Hola

Respecto a la primera: el ajuste de hiperparámetros queda a elección suya, lo importante es que justifiquen porqué ajustaron, o no, esos en especifico. Por ejemplo, la profundidad de un árbol y el C de SVM tienen un significado interpretable que sería bueno que mencionaran. 

Por otra parte, los algoritmos a veces tienen hiperparámetros cuyo valor no vale la pena ajustar y tiene sentido que queden en None (asumiendo que toma un valor por defecto).

Espero que eso responda sus preguntas, lo importante es que dejen bien explicado su razonamiento (explotando que un jupyter notebook permite mezclar tanto código como texto)

**Comment by fran-gl** [comment]
Oka, muchas gracias!
