### ISSUE TITLE
[T3] Problema con usar en_core_web_md

### ISSUE THREAD

**Issue by simone1919** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#93]
Hola! tengo problemas con usar el  "en_core_web_md". Me tira el siguiente error:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/61993603/173123006-9d4bb495-8fb5-47ed-aac4-0ecd6cf15548.png">
Intenté instalándolo en la cmd, pero el error sigue. Lo extraño es que no tengo ningún problema al usar en_core_web_sm.

**Comment by anibalcontreras** [comment]
Me pasó lo mismo, si al instalar te tira error se debe a que tu versión de python no soporta la librería. Según busqué en internet se debe tener tener una versión de python mayor o igual a python 3.7.2. Yo actualicé a python 3.7.7 y ya no tuve el problema.

**Comment by FeBalla** [comment]
Complementando la respuesta de Aníbal, por si no te funciona, puede ser que tengas más de una versión de Python o no lo tengas añadido al path (variables de entorno).
