### ISSUE TITLE
[T3] Problema para descargar 'en_core_web_md'

### ISSUE THREAD

**Issue by tomasernst** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#94]
Hola!
Pude descargar e importar correctamente spacy, pero al momento de tratar de instalar 'en_core_web_md' me dice que no existe el módulo spacy. 
Qué estoy haciendo mal?
![Captura de Pantalla 2022-06-10 a la(s) 17 16 55](https://user-images.githubusercontent.com/80714248/173152324-bef28486-eeeb-4bc9-8c33-1de772ecd956.png)
PD: Traté de correrlo en el jupyter notebook y en el terminal, también probé utilizando el comando con python3 pero nada funciona.

**Comment by FeBalla** [comment]
El problema es que estás ejecutando el comando en el notebook y debes ejecutarlo en la terminal, porque no es un código de Python, sino que un script de la consola. Ese comando debes correrlo después de hacer la instalación de spaCy con pip.

En teoría, debería funcionarte con python o python3, así que si no te funciona con eso, es probable que:
- Sea tu versión de Python incompatible
- Tengas más de una versión y se está instalando en la que no estás usando
- No tengas Python en las variables de entorno (path)

**Comment by tomasernst** [comment]
Y cómo podría saber en qué versión de python la estoy instalando, cómo manejo eso? o cómo la puedo instalar en la que necesito?
Llevo mucho tiempo tratando de hacer esto y no he podido avanza en mi tarea, así que cualquier sugerencia sería apreciada.

**Comment by tomasernst** [comment]
Finalmente pude descargar en_core_web_md en el terminal. Para esto tuve que descargar nuevamente spacy usando `python -m pip install <pkg>` y luego `python -m spacy download en_core_web_md`. Pero ahora tengo el problema de que en el notebook de jupyter no puede encontrar el modelo.

Cómo puedo hacer para agregarlo al path? (a las variables de entorno como lo mencionabas en otra issue). Ya que `nlp = spacy.load('en_core_web_md')` me funciona perfecto cuando corro python en el terminal, pero no cuando lo trato de utilizarlo en el notebook como mencione previamente.

**Comment by anais-mv** [comment]
tengo el mismo problema, instalé spacy con la cmd pero el jupyter notebook me dice `ModuleNotFoundError: No module named 'spacy'`

**Comment by FeBalla** [comment]
Es difícil saber el motivo exacto de su problema, pues la instalación de librerías suele tener algunas complicaciones. En este _[stackoverflow](https://stackoverflow.com/questions/54334304/spacy-cant-find-model-en-core-web-sm-on-windows-10-and-python-3-5-3-anacon)_ hay varias personas comentando distintas soluciones, entre las que destaco:
- Reiniciar el ambiente de jupyter notebook con Ctrl + M + .
- Probar con importarlo directo, algo del tipo:
```py
import en_core_web_md
nlp = en_core_web_md.load()
```
- Verificar la versión de Python que está usando Jupyter Notebook y que sea la misma que tienes para lo demás.
