### ISSUE TITLE
[T3] Árboles de decisión Actividad 6 - Pesos CustomRandomForest

### ISSUE THREAD

**Issue by fguinez** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#97]
Hola!

Cuando se nos pide ponderar las probabilidades por unos pesos w1, w2 y w3, tales que su suma sea igual a 1, ¿estos pesos deben ser ingresados como un hiperparámetro?

De ser así, ¿los dejamos como un hiperparámetro de la clase o del método `predict`?

**Comment by FeBalla** [comment]
Es un ensamblaje muy básico, así que la verdad da lo mismo. Por comodidad, considero mejor dejarlos como atributo de la clase, pero lo importante es que quede claro.

**Comment by fguinez** [comment]
Gracias!
