### ISSUE TITLE
Base de datos GTZAN

### ISSUE THREAD

**Issue by ignacioarteaga99** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#98]
Hola, estoy tratando de cargar la base de datos GTZAN en mi archivo jupyter para poder utilizarla en la actividad 1, pero no logro que me cargue. 
Hice lo siguiente:
**import tensorflow_datasets as tfds**
**df = tfds.load("GTZAN")**

¿Cómo se carga ese set de datos? Ni siquiera encuentro información en la librería para hacerlo

**Comment by ignacioarteaga99** [comment]
Me aparece que "gtzan" se encuentra en la librería:
![image](https://user-images.githubusercontent.com/48535635/174359062-2b24cf98-4613-44e5-90f5-ff714ec2e865.png)

El problema es cuando trato de cargarlo:
![image](https://user-images.githubusercontent.com/48535635/174362525-a4daf4ac-3c7c-4cb8-8687-b5465ea0bbea.png)

Me imagino que es porque es muy pesado o no sé, pero no puedo acceder a los datos y me gustaría hacerlo para poder escoger una canción de ahí y hacer la actividad 1:
![image](https://user-images.githubusercontent.com/48535635/174365157-dd965237-3852-4973-be23-b155b26ab553.png)

**Comment by FeBalla** [comment]
Hola! El link al _dataset_ en Kaggle está en las referencias del enunciado. No es necesario que lo descargues completo, sino que basta con 1 canción. Recuerda además que no debes adjuntarla en el repositorio, ya que con el nombre nos va a bastar para hallarla.

**Comment by vicentevegaulloa** [comment]
[Este](https://www.kaggle.com/datasets/andradaolteanu/gtzan-dataset-music-genre-classification) es el link.

**Comment by ignacioarteaga99** [comment]
Okey, gracias. Pero entonces tendría que descargar el _dataset_ de 1.2 Gb sólo para utilizar una canción? No me queda claro eso porque en la página de Kaggle no encuentro la opción de descargar una única canción

**Comment by FeBalla** [comment]
Probablemente, después pueden borrarlo de todos modos

**Comment by ignacioarteaga99** [comment]
Okey gracias!
