### ISSUE TITLE
Dimensiones Red Neuronal

### ISSUE THREAD

**Issue by ignacioarteaga99** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#99]
En la actividad 3 de la parte 1 de la Tarea 4 tengo dudas respecto a las dimensiones que se le entregan a la red neuronal. Inicie con un modelo secuencial de red neuronal, al cual le agregué una capa densa con un `input_shape` = (130, 13, 1) [el del x_train] y `activation` = relu,  y luego otra capa densa  con 10 nodos y `activation` = softmax.

Las dimensiones de mi `y_train` [pasé el y a categorical] y `x_train` son (7000, 10) y (7000, 130, 13, 1), respectivamente. Y estoy teniendo problemas a la hora de entrenar (fit) mi modelo.

Hago lo siguiente:
** model_1.fit(x_train, y_train, epochs = 5, batch_size=128) **

y me retorna un `ValueError`:
**ValueError: Shapes (None, 10) and (None, 130, 13, 10) are incompatible**

No entiendo muy bien el tema de las dimensiones de ambos arrays y si es que el problema va por ese lado. Gracias!

**Comment by FeBalla** [comment]
Sin tener mucho acceso al código, los motivos pueden ser varios, pero recomendaría revisar lo siguiente:
- Revisar que se esté cargando bien el _dataset_.
- Revisar que todo tenga las dimensiones que señalas acá, que parecen estar bien.
- Este problema se puede dar también cuando TensorFlow entiende los valores que le estás dando de etiquetas son un _int_ y no una categoría, es decir, cree que debe hacer una regresión para un valor en vez de clasificar. Para solucionar esto, puedes usar `to_categorical` (más información [aquí](https://stackoverflow.com/questions/61550026/valueerror-shapes-none-1-and-none-3-are-incompatible))

**Comment by fran-gl** [comment]
Hola! Me estaba ocurriendo lo mismo y vi que en la ayudantía 10 "aplanan" el input de una matriz a un vector. ¿Deberíamos hacer algo parecido en nuestro caso o no es necesario? Porque me parece que ahí se soluciona el error.

Muchas gracias de antemano.

**Comment by FeBalla** [comment]
> Hola! Me estaba ocurriendo lo mismo y vi que en la ayudantía 10 "aplanan" el input de una matriz a un vector. ¿Deberíamos hacer algo parecido en nuestro caso o no es necesario? Porque me parece que ahí se soluciona el error.
> 
> Muchas gracias de antemano.

Pueden hacer lo que quieran, siempre y cuando justifiquen el motivo y sepan por qué. Para redes convolucionales lo de aplanar es esperable, de hecho, se ve en las cápsulas de este tópico. En la red densa me genera dudas por qué necesitarían eso. Si tienen el _input shape_ bien definido no debería ser realmente necesario 😕

**Comment by fran-gl** [comment]
Aa yap, muchas gracias!

**Comment by smrebolledo** [comment]
> > Hola! Me estaba ocurriendo lo mismo y vi que en la ayudantía 10 "aplanan" el input de una matriz a un vector. ¿Deberíamos hacer algo parecido en nuestro caso o no es necesario? Porque me parece que ahí se soluciona el error.
> > Muchas gracias de antemano.
> 
> Pueden hacer lo que quieran, siempre y cuando justifiquen el motivo y sepan por qué. Para redes convolucionales lo de aplanar es esperable, de hecho, se ve en las cápsulas de este tópico. En la red densa me genera dudas por qué necesitarían eso. Si tienen el _input shape_ bien definido no debería ser realmente necesario 😕

hola, me genera un poco de confusión este comentario porque en los ejemplos que nos dan en la red densa si "aplanan" el input y en la convolucional no lo hacen.
